services:
  snowfall-image:
    extends:  # Logging definition
      file: ../include/logger.yaml
      service: loki-log-driver
    build:  # Docker Image definition
      context: ../../mudev_backend
      dockerfile: ../mudev_backend/infra/Dockerfile
      target: runtime
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - /Volumes/storageB:/user_content
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /
    depends_on:
      mulab-postgres:
        condition: service_healthy
      mulab-redis:
        condition: service_healthy
      mulab-loki:
        condition: service_healthy
