version: "3.9"

services:
  mulab-prometheus:
    extends:
      file: ../include/logger.yaml
      service: loki-log-driver

    image: prom/prometheus:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    command: >
      --config.file=/etc/prometheus/prometheus.yaml
      --web.config.file=/etc/prometheus/web.yaml
    expose:
      - 9090
    volumes:
      - ../file/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ../file/prometheus/web.yaml:/etc/prometheus/web.yaml
    networks:
      grafana:
        aliases:
          - mulab-prometheus
