version: "3.9"

include:
  - path: ./loki.yaml
  - path: ./docker-prometheus.yaml

services:
  mulab-grafana:
    extends:
      file: ./include/logger.yaml
      service: loki-log-driver

    image: grafana/grafana:10.3.1
    platform: linux/arm64
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - ../file/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ../file/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    links:
      - mulab-loki:mulab-loki
      - mulab-prometheus:mulab-prometheus
      - mulab-postgres:mulab-postgres
      - mulab-redis:mulab-redis
    depends_on:
      mulab-loki:  # Loki must be started before services for log driver
        condition: service_healthy
      mulab-prometheus:
        condition: service_healthy
      mulab-postgres:  # For accessing Grafana configuration
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_INSTALL_PLUGINS: grafana-clock-panel
    networks:
      reverse-proxy:  # For reverse-proxying on NGINX
        aliases:
          - mulab-grafana
      grafana:  # For accessing loki and prometheus
