version: "3.9"

services:
  mulab-loki:
    extends:
      file: ./include/logger.yaml
      service: json-log-driver

    image: grafana/loki:2.9.4
    platform: linux/arm64
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - loki-data:/loki
      - ../file/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      reverse-proxy:  # For reverse-proxying on NGINX
        aliases:
          - mulab-loki
      grafana:  # For provisioning as datasource on grafana and allow promtail to access
        aliases:
          - mulab-loki
