version: '3.9'

services:
  mulab-promtail:
    image: grafana/promtail
    platform: linux/arm64
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    expose:
    - 3100
    volumes:
    - ../file/promtail/config.yml:/etc/promtail/config.yml:ro
    links:
      - mulab-loki:mulab-loki
    networks:
      grafana:  # For accessing to loki to send log
