version: '3.9'

services:
  mulab-api:
    container_name: mulab-api
    extends:
      file: ./include/application_image.yaml
      service: snowfall-image
    env_file:
      - ../build/dotenv/mudev_backend.env

    ports:
      - ${HOST}:${PORT}:${PORT}
    command:
      - python3.11
      - -m
      - gunicorn
      - "--bind"
      - "0.0.0.0:${PORT}"
      - app:create_app()
      - --worker-class
      - uvicorn.workers.UvicornWorker
    tty: true
    healthcheck:
      test:
        - CMD
        - curl
        - -sf
        - --max-time
        - "5"
        - http://localhost:28000/livez
      interval: 1s
      timeout: 6s
      retries: 5
    volumes: []
    links:
      - mulab-postgres:mulab-postgres
      - mulab-redis:mulab-redis
    networks:
      reverse-proxy:  # For reverse-proxying
        aliases:
          - mulab-api
      web-service:  # For accessing to PostgreSQL and Redis

  # mulab-celery-beat:
  #   container_name: mulab-celery-beat
  #   extends:
  #     file: ./include/application_image.yaml
  #     service: snowfall-image
  #   env_file:
  #     - ../build/dotenv/mudev_backend.env
  #   command:
  #     - python3.11
  #     - -m
  #     - app.celery_task
  #     - beat
  #   ports:
  #     - 127.0.0.1:28001:28001
  #   # healthcheck:
  #   #   # test: ["CMD-SHELL", "celery", "inspect", "ping", "-A", "app.worker"]
  #   #   interval: 10s
  #   #   timeout: 6s
  #   #   retries: 5

  # mulab-celery-flower:
  #   container_name: mulab-celery-flower
  #   extends:
  #     file: ./include/application_image.yaml
  #     service: snowfall-image
  #   env_file:
  #     - ../build/dotenv/mudev_backend.env
  #   command:
  #     - python3.11
  #     - -m
  #     - app.celery_task
  #     - flower
  #   ports:
  #     - 127.0.0.1:28002:28002
  #   # healthcheck:
  #   #   # test: ["CMD-SHELL", "celery", "inspect", "ping", "-A", "app.worker"]
  #   #   interval: 10s
  #   #   timeout: 6s
  #   #   retries: 5
