global:
  scrape_interval: 5s  # 5초 마다 Metric을 Pulling
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
    - targets:
      - host.docker.internal:9100  # Docker 컨테이너의 호스트
