service:
    #ENC[AES256_GCM,data:/s5Gcx7xL+qenvHfVkajP3g9r14+,iv:xltpUKM+xzEDGxdHDFIrPei6z8bVLh3AxaVkmFagn5c=,tag:mBxohc9yOKuX+oz0FX3BaA==,type:comment]
    #ENC[AES256_GCM,data:GnDVhBFtdDjMJu/p,iv:ccdT6L3HPpnkP3lPiqedGE7FZakywfZ3dWeAtvtA7LI=,tag:zYLy+s56DvKquN2MWxqSzA==,type:comment]
    #ENC[AES256_GCM,data:C24quaLHzaQP7zy30u05sT28l98z,iv:QVbIcbRzonydEsBowlDJqk5Is7e2bChrlYuHJZ4hTV8=,tag:KFtkgTtKZmEZy7vDk2jdaQ==,type:comment]
    #ENC[AES256_GCM,data:3ZL8/ywBpWpICDwYbcM0tEZlOTYFmmcraQ==,iv:dvyUQVD9N2z62xw62ZtHLhO9KSkRmw3CPgUlMmgDaow=,tag:ZRIfyZLnvVE9ADTKtxmWpA==,type:comment]
    #ENC[AES256_GCM,data:EYwTnU3IgG7w+ekEHm12Xr+Co0L8nHw6SbjRZ/w+OHswIutDweA8m72a+ntcU/yxV7w9,iv:IIbJlhiPuwvAcXofY0wrYtjpbrlVm1z5x2JJV+oklTQ=,tag:JzeyqPCTB+ttph6lfXsvgw==,type:comment]
    #ENC[AES256_GCM,data:ZITK0Oi07RVw+P6Ep4ajokaD+azo,iv:ggdRWZ4k7g7Ty1fiiph60g0nx9T2H2YCdRzEDYY2Rvs=,tag:PsGYiPm3Iu8aBwnmjP5VRA==,type:comment]
    #ENC[AES256_GCM,data:/5z3YnKMrtlvEz9Om9WdDtZW/gDWET90,iv:4hw7N3aanbX0DDD1EZ04RcGbntvtLh+z4THqg0YQDLM=,tag:k9s9aIuQ4tLU2ECqIV7Oag==,type:comment]
    #ENC[AES256_GCM,data:j7rrclapfaDNxE6ryj4CVrj9jMgkR9BsHmqSUEUwAD4s7iriwrvnSGc6vvFGgSNCHTA=,iv:lMu4fXEsZlFYDNGNtzw12cob3kwa20SZXgh1FDvm7gE=,tag:myjwqY4bFXuGIzYNobDvgQ==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:8i/bTQGfjmRpKldi3jEj/E7wQV/PST03ClQ94s5KPCnC3jveZdBXlcv+vqSI8QOvMKahRcZAVzLJK4gxQuOChg==,iv:F/KZ4V38b9IGXw4NAf5Ch5MtDi1gR2TEILHWbQjPzuY=,tag:CJ4opb/ZOW677aZV3Zk6lw==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:P7edEm7t0qDOhMwNaFXsYIQjjtCtu9YFUSyCEOLwwVKSXj0v9lXTKOENbXAkWK7rCDSThQnxU6QqXYhLDVDANYi8TA==,iv:KGGP0CM8XNxoZ3+5cNAQ011dWL166Lo1U6W/E6J5g88=,tag:l9ddsyr5S8s+vppk2cpP4g==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:+XFOhbKkOgCYIxgO8tOHHlZjTo4PeqDgdDYTHp+5CmToXax7F7MT6nxPZyGzhWNixclerKduQTByI+XC0c2iPq/oVY+X7A==,iv:iT54VrVhLJyCKzv66nUdMaOXW076wESj1Hn8dz16O5k=,tag:sKp7/Wy75zaGNdU27qnkUg==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:aKrm/nv2ur3fhwoDv3iIGTm4dMeeWKFnIYCv66rIs8Yy0DcsFNnq4Kt2gYd1QdBHiKYL2gU=,iv:2gVEfEysxH6SLG3RhLrHiDbjwtsF+NNP3tsEicUkO1c=,tag:o0Hha89AlnVLycprygCKMA==,type:str]
            - ENC[AES256_GCM,data:tzDQr1re8gr0kcdWgOl5Mvc2TjloheCKS3p8FLYbo/18TtJ0n610+CXotiJm2pbogxr9/Q==,iv:8oyARN8Mq2VEwNPn/IDjGWbE/d4ATUXJ2nlw0ZgIZpk=,tag:z0A7AIzLjGp5XQKoK13KFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWHRpTXNRMWxiVVhjYmlG
            TlJ1U2NxYXNCWjBLU1NvUnUwc3hGRU5iR2tJCndtTDdXYWZ5ZFEzTWI1VzR1WjRH
            N3J4TWYxWkxoTS9HY3JnZGg0YnhQMVUKLS0tIFFsaFl3UFA4NVFTVHhBTFRaREkr
            YUV4clFFT2RjaXJrekkxUk01WSsreU0KjzOfyhoI9oHYla9sXZW3l+JEwlOQGrS9
            UDxLqyiSJujVNM3f1xkS90A32KV1ZOc+A3qziicj1bD/9iSwurMWOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RlE1WHpYaFNLLzU0U1FW
            UGIvaWxIUjM1WHkyN0lJYkd1NUlmRHp4OEJnCnFvR2xWRWlBc0NkMVRjalIxMnRG
            ZituZFFMTW1YRkJLZ2p1M1kwZXlWTUUKLS0tIG43Vm95VlJRNTVCc2xvU2pZWXBJ
            VTJLeTkzS0VsejJPdnFzcUFST3E5UHcKjgYUufZ3dV7Yh3EMSC3Nmt2NJwAajn/6
            TQb5DiaWXdiUQV63GTT/Y/RuBoYnoMtHnoCRl1Te4v1Kh1aOE8BOqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T14:04:33Z"
    mac: ENC[AES256_GCM,data:3WvojckEdruFk5yqWndO2249xada/tuznh3YbR0kOkYgG7lscFAinHy5cwdjv/GI9d7tVI/lj0DDGF5PWdn1gxJUnMnFj6R+kCdm6G3SSgEF80c98cpocu8pyRsn9142eXS31H1FhUk4Q/BETZc+oXwWOfNTWLiAEAqW0DiOjfo=,iv:/abqc/XFUWTW4MVNHpoQtI5Otck+wkP9cJf3ghuhpH0=,tag:SOyFjFBlvaVluSOiP92ecA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
