service:
    backend.$color.yaml:
        matrix:
            - variables:
                color: ENC[AES256_GCM,data:cl0rO78=,iv:+LyaO5yEy3J9juyW4ZOCz8xARI/ZRlVQ97XEMM+H/9Y=,tag:Us7VG1luMTdz2hhYXIkm0g==,type:str]
                port: ENC[AES256_GCM,data:nHG9RbLpcCBX3ryQkioxRdtVdNCKsQkHcBpbLfkI,iv:JPYd8ga3N3g0cKlzPfaXzbVmvg8VY0yKLnSXwGg1Zug=,tag:pxrEFya9T7N9Znp1wACX/A==,type:str]
            - variables:
                color: ENC[AES256_GCM,data:0cBfzQ==,iv:FMQbwoFlP72tD11idKQJmajOyKQC61VVXqxeBJ5xi08=,tag:pOPXTPmcksTwMO8QFBC19A==,type:str]
                port: ENC[AES256_GCM,data:ntmFDPa0YKrPlDB2onTVGbHa9SP2oYZTTlN9vtw=,iv:f3vfu7Gqz0MsCTbZijtmUquwU2hbOO0gRZU1yUgjGaE=,tag:yyO0uZ6WmkbIzWrhjFSDEg==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:rL7XbyQLt+yCrosQACABPNjyPstWMRXyf4eFrqVnNJLJDTn0wZljmlVIEoSfqK71pjPq2Nk=,iv:i6JpbgAhf/BSrIFnAQdtLZ5Gm9Q/CLEfTif9RIPxvdQ=,tag:fUzpIhQHSx17XOr4frs3qw==,type:str]
            - ENC[AES256_GCM,data:9QgPIqus7jOEXVo7fa2dqoueWGdi3L5KZfelZVYXMRo49y7NOkZLZaHEzcm4Da3UpxtKGw==,iv:ioj0wI1j9M0NnCsN+1LucCqwgP5WF2YjJxTW62WGl94=,tag:RnNssSIe11YRUZZytCQqWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Nk9md1RkU0UwNjd6REJ6
            OUE0R1Nwcm96UDQ3RmFMZ3NHZjl4aFN3YXdzCkNCaWxYR0cxSDh6Q3NMWFlRQi9Q
            cGJjSEVZSU0zdkdNVlJySy9JSEpNVzQKLS0tIGV0aFZHUGt3UE5GbWhtM09FUGQx
            QVg0dUZWV0p0SXhEUVgwWXJrRFJGQVkKAMhzcew3mAGJZfjo9ravEaLkelf1velr
            6sI1zpZgRTl2Z76pHaxoSt6lY7uMCh1HP89ocKv50m+My2wvddONPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaHgxVlZKYkMweE1UaFBi
            Yy9KeFlVZWMxUHBaWmFUWjAwQlFLYmx4cGpnCmRCRTM3NkgxOXVUYlRabFVMWDFq
            WUNhNDlxanptNys3b1czUDBvdWVPNkkKLS0tIHkvNWNYQXhhMnFlUXI2a21ZSkl0
            L1dPQVo5ODdsSk9aL3hMVVZjb3RURFkKMh0mK7N7X/IWwYF9tRfbsyFvkMvUKvlN
            DY3XlRSFfjwo4jGUtjXERgz9Rl3cWvQMpyhQThgk4ETP3C195xn3BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-18T14:35:32Z"
    mac: ENC[AES256_GCM,data:EJVOhKgvBS1Mlyvl+6NkW1AD7c7jdo/B6463v9Jqe/oDRtWRDeCkvQzrrVA+DGVM9pjoxnNqGB0vBpFOTa2lwDM8EiYDZfRtrulTfIrtJdCuoPisdT4oGqnn3Nr6tZOwJqZQ3aJB2VKIJVCJSEqLi/3hGp9SGBOxSkR1UQRZ9nc=,iv:UlK46lCAb0m2MgGb6MgUcz6DsxGqwXmyO3qvk9Gzyvc=,tag:hfxfMU3b/m0OQVgUArwzSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
