service:
    #ENC[AES256_GCM,data:GlKlFwXo+gmRyp3sju+iMR9GAilB,iv:Gw6zL4zsf35ERbygZh+jZjXa7IR9Q+zYgoT2cPYubVs=,tag:o0o3NsxVi5CbxDRr2/GeZw==,type:comment]
    #ENC[AES256_GCM,data:tyEjn65SgH7OWfge,iv:KLBOv79R5qwMtqcJEw2CGdbJ9RjTyOmMgy+gWZkOvvY=,tag:3wtM6H4UPAY9ldZYe9sVVQ==,type:comment]
    #ENC[AES256_GCM,data:74wRGcMb1KN5AaF2VnD+Y/Is2C9F,iv:nL4/s4Xxs1Pg9jzhRnXzo56nndKyVrtp6bAxVniTaL8=,tag:TicAFSEHjjo5ydLiFI0LMw==,type:comment]
    #ENC[AES256_GCM,data:3SCNKy2a4npXysgw7Bo8s34gFcwYyRgWfQ==,iv:vIpBqLEnzD/YAEB1t6wQXKfbO/DR29SwJprP9dUCdKc=,tag:nEVu5EXQcwUPnkjyku8Dbw==,type:comment]
    #ENC[AES256_GCM,data:hwZ3RwJ3a5csIMKiu8lMmkqwa9sNqaWrj8WtUPGorJa/y3gwnytllH5Q5RyK4GEumSaU,iv:PectnlU2dFa097tnP+5R/DUgea1SO/fIHHYLKU7lrtI=,tag:TTy8beYfl3gKX4RmMvwUIA==,type:comment]
    #ENC[AES256_GCM,data:UwcTnVq4YaCuq2O+PDHrnWZIlCdN,iv:SeT8/v6PwSK+mOrZPDQO83AzDVdhy2Mmt1uVMTmA75k=,tag:Q7r0L4xpocPMTQagW1smSw==,type:comment]
    #ENC[AES256_GCM,data:/AMgyeznlOVZ/sWHzUTnv7H/Ohjh/X/G,iv:mSij7A/4W4F8GUa1aoFFkuXCD/n3qAcUs9hSxasfyp0=,tag:PJIjPEfYkLLa5c2JFO+3PQ==,type:comment]
    #ENC[AES256_GCM,data:3dVp8233OuH0RaSHOqstHvGasoBo1Lc02TVB3GTWTPL4QlSrB1ZDKB7YEhQF03kMnDM=,iv:zXn7zrqHWvi9/kyqI1jilU80U7ErY+DIPvlkPjOTrvw=,tag:2gSfh3djbuDqOtWG7zsVWQ==,type:comment]
    jupyterlab.yaml: {}
    node_exporter.yaml: {}
    ssh_vultr_tunnel.yaml: {}
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:YVWFMCoMgK+cD3FIcpRbAuILyRbmGOtJc7F0GGX8uaGLKCq0UWDXbk0CaSh4O/QEftL9JvY=,iv:1VuYfAtXjuBRaGZWCl6/GbWcen89Of3NuwrHShnQNio=,tag:0HTktaDx62OtexqcEZVTJg==,type:str]
            - ENC[AES256_GCM,data:Puqa/c21nzCRPdSh4MKL/79IQFSyjQRk+5GZPTKnCtmGUiKcahXy+eSAoZ0N2yRy3p8tAg==,iv:3gA0D9PUwFHV8PNuYAKcYLjNVaPItcSH5JTlxp/UwN4=,tag:7XN1dAB6nRYzofu17tr0ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjLzJNS0kvNTgvNURFVEM5
            TWdGeGdRYndxdWk2WUxzTGV3dE85eXpZY2xRCkFMZkwyVkRXUHlsTHFMYkVBZ1c3
            S2JNZkpNRGNhZ1h1ZlpkOWcvdmFGdFkKLS0tIDdpNDFkb2dldldLRUlxQ2JyMmly
            TG1oZ0IxRjRDUVcwMktndUhXU1ExZEEK4qndMOLmuLLLgfGdh3hzK6n8VKTJ/EBn
            87SgJI3LUhFxv46khrITAIZYbBOcc3k7S3hWt04iabnz9pntuyvPng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZHpsZmxPSUZ2OEtCajkz
            SVBNeDk0VWlDTWVYcXY5OHpad0VvTDlTb3lnCkIrdGNjREEwWjNQU3lBQ1BCWDlz
            a0pDSnExV1ZTV0tKekdOSEJ6b2FCSGsKLS0tIFU2bXRhQWFYNXNadlZtUFNHMXdK
            MXQ1VEZNZ1ZlNTRsM2wzQTBOMmM4L3cKKfl9cUs6d4CkDUqZmj2QuX50f3yWbn3t
            cotrP4KK2AIO6O9y4WmhiAikJnP/DgBh1o/55uL1F3EliyWlVr65CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T13:56:43Z"
    mac: ENC[AES256_GCM,data:u1Tw891xlGrJNXX5klkU0OMhtsWTtWUcAAbaWAeUI0fIvbCT8F+tIR0ZOw7rt+XCAfLW7bomoQLkHGUfU/33M1HtWG3u67CQlCbYAmjqsgTrWK3kXPtykMuCGls93ggHjCzFqWSSwIJjT/nOGxbgYTK3K8/5cDoJqOSQRpQpODA=,iv:0YJJ+1tWw44zYMDY6gyZrhPaV6nTd6XqHWLU3Wu58Lc=,tag:Hv99WhSVC4dwC2qZx5ZyeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
