service:
    #ENC[AES256_GCM,data:YUsw0NCRya6hdXgKwVga6Wkqk4+a,iv:9Arvvzms+FmkxjlY4tLfnz5aSFkciRVMQwNLvSKkYNM=,tag:2kOhz6aJ31APfo79df7GAQ==,type:comment]
    #ENC[AES256_GCM,data:vFOPRf2tsSRxdv5Y,iv:pzQAE0v1RIUJnFq61Jpz1nbOrNrj5vX1ReOcYhiCV54=,tag:VzNiavIWx956b4pXVvW5/Q==,type:comment]
    #ENC[AES256_GCM,data:iebO8A5FzIv6zN9wtjVQlvNbt7+z,iv:D2pAEP0GZ4IRbmnSalGoaeVQCPTP6sa9FlAN5a2KBPs=,tag:tNvnIhnxyQ/o/vYs1EUmeA==,type:comment]
    #ENC[AES256_GCM,data:vwTk+0QSUVxpfCpzVvJbq1rU2AIAF52QNA==,iv:tPqnKAQOnxVZsWkQxuTWeEuSCopJ2VKLUs0MIq+IHf0=,tag:EYGj/vb11o10tdR+BljwaA==,type:comment]
    #ENC[AES256_GCM,data:G7A+H0WGSWgJeaLgU8plataB8X9ZtjZZ7rMGtakh/GdANCM+r2okwO1IVdhvbEOucpfF,iv:OEHvyNCRTXVfvbo5x7d9u+ifmq3CNxx5KC4ZZERCzb8=,tag:ScBsLgPSGsBdNSzwONOnXA==,type:comment]
    #ENC[AES256_GCM,data:qLslHaf6P9b/erGjnwSQu8tPm+2C,iv:ZL5FaeughowSa5R9FGiZsLYcpEr1SJl11V63/Fdmnp0=,tag:UfjBCG2C5aGcZGJ5aNGipw==,type:comment]
    #ENC[AES256_GCM,data:S94T+Wdw6yPtVGA0NnAxjIBGhJxYVHwD,iv:Jb95LgJPmEtplKDtVLuK2YX8DOGyi+vdVcDqbfp31ro=,tag:hGvrsaTs0BSeSDGqGbbI5g==,type:comment]
    #ENC[AES256_GCM,data:FLGQuNrwfKg3Z+uSfkVhVdJ5jdsPY7YSEiGppYPgKOs9zk9MBJFk9QDuAev0HKDRIMg=,iv:0jwHFDssAwzr5XOPcqd3qlkgAA++XkxnIZuurYAIo7E=,tag:KYhuKRbPc5ozpb5DVUzU8w==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:QAtcKxZHWMGuUw4bfM8hpjfW0zFZEmdtnss0NfBaHw3PVH+2gO98ITfm37muT3PAGIBI638iJ/u1wY5o59rFYg==,iv:XRc4W0TZ0X+0Axrcy7ku4GczyDUX6b2meiPjXWs6FNI=,tag:1nSTm8LRnQwq0ZmXd9r2ZA==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:QOYVQkmfh8G+JiD3miZwwoMSA6OHCU6bnt585GX3ZLm1oWIfmnGHxnKl28/KCzswSS/mZvrfQAQHMjwUnOA4f4na2A==,iv:DsAOfG9tYCq4x94UM58BRzQxGbtq6HsMhvoN4JyfNw8=,tag:qNzPVzaOV67AchzuJvgg0g==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:aln2jgEliXL8SMEQjCvcrhfmO1cDVP74dK+a8rKbn1oDMR56+gE52qjSupHcFAhF4wMAXDSPOvq/DenmJ4jdRE1stLlIuQ==,iv:mqRa2u0WTyGigV+9wgJ/9dBYjrm+n2jlgZLojCqP9UQ=,tag:x93Qc6aWHvIH5Cwn5mWiag==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:8mtZi7wMX4V3EVwBQGYFYDEB/Q==,iv:A7upwVdvwO6I00D95ID8X03yRNbKOOLwkMBUWuIoSaM=,tag:PYBwxn/rsUk32iOOkJwO9Q==,type:comment]
#ENC[AES256_GCM,data:kJv051YIAYGe6SAD,iv:5pwh0gMNqowPDdP2pymyfacTXsVezBcKPqG4Ixybd/U=,tag:GJvfS1mxiYhb2pG93xpvuw==,type:comment]
#ENC[AES256_GCM,data:ZXrHi0QQ8VXuVwOFn6Ru+yFn1e6k3cg0YTi9RjUedi+Zf0k6PAcnDfe5uSY8/t7Cq6q70SENIBn1vLBZclXU9g==,iv:t+AU3GY06Zn2N0Ubd071LCcj+DIDOlskAdzXEv1Gxsw=,tag:MD6FqfH2rSN0dk5472FAUQ==,type:comment]
#ENC[AES256_GCM,data:97WgU5SEyEJwd5Lswho2i0KtFa8XRvXZPRTksefSBFoWw6WEZr/2sZa5ENdq9pE3i0vaE2TqEyjQSUht5MAk,iv:NdysulyzAOJq66LAiU66nSJiwZGHqkQe3oWDZ5j6QlY=,tag:sdwZivbajz7Vjf7gGaiBFA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb3JYajdWV2drVEVxVFYr
            bmFWNTZTcTRxVDI5ZHNmK053QnErTGJzbERVCkVpbWZTcGVNTmZ3SFFsQ010Q01O
            QWFRSmZXUVI2ZENjVmZWY3cvOFJOWHcKLS0tIEQzZ3c0U25ZUEFJbmtBUU9qYTVR
            dHRPdGU2NVFDa09GdHdzek55NFpubGsKWJe6gcDKi8mQ4pwis8jDNVFQOrc+QUKO
            aPu6FsPn8hBIPWBmddfVhpsFotTcjhXRmXOQA9PC1murYNXxtGuwmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRnY3V2FKQkFEN2dyZ0Iz
            Ry9xbTZCMnFLYjcyUzJrS0JLdjRoNjlIdGpzCkw3bThsRXd3Z0lmczdHdzlGdmxH
            aFdHUENVS3N6cnVxUk1lM2lKcnBJVlkKLS0tIDZocFl2aHh6bVcydmxwY29DOStQ
            WjF5bU5VbThkN0RjaGdTTDJxMk4yWkkKMP4HOJjJynfvynmhzPdIwKQhtjBvBLbo
            Gqb6fmr1O2qTmKLh48SQG8fGCiKUtUHc7G7aInCRuG7yrk1+v587Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T14:03:22Z"
    mac: ENC[AES256_GCM,data:wDT9qVKUiKAYEWC7jnj/sJmTpp35SdJBfvF5FseK3m3fi9YB3VKZzIWCgDug6sdPNWTruS6u3XwasnS8/1G+0P0CzydF8THL51M12gGZWCGUPqBX2eJade0hZWTg4rYqRF8JUWPb2a7w7WVEXcewupxGtE66S7evnNa3Mv7X9Io=,iv:hUG6KkWd2UJplLci4wej1GCGQOfbWfZvC6nJHJ0P59k=,tag:X5rOoXuFCRYxWRitJ9CyeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
