service:
    #ENC[AES256_GCM,data:lP4KgUm+AJxHkCmhgO7i0O63pbfq,iv:g19ufBJQd3xfulkPrP5oj9s2mSnEBs/+aIMzJUKtoOE=,tag:x3uea9QoW3tjzwBWe3hVow==,type:comment]
    #ENC[AES256_GCM,data:P0n0zebm0OYhtlSL,iv:dv2MvZ5XWMd9p63YWDFwi9lJ8wf3VguFnEqatiOQsBQ=,tag:bfREV1w594zymI+N/fMf5Q==,type:comment]
    #ENC[AES256_GCM,data:d71y8oWtVMxPrw1xix+ydvuWQV9+,iv:wUwLlyr+C2xIKIAwSTvma+EXw71ZFjKsO+0bGBkd7GE=,tag:wNQk2tm8r8krnZmMAAHa5w==,type:comment]
    #ENC[AES256_GCM,data:aaa08i1q+EglCASs9TdMoP46WTfm+P60Ig==,iv:BEJpKbo8kJNr/YJLEzgwLeqkbj56c2JNs7yvfK8lAEk=,tag:fWCOvpsYRAsp0yXAg9e2QQ==,type:comment]
    #ENC[AES256_GCM,data:MpaEMESi/pX8Cc4QgfIwBiaF573DGyNqZYzm71HCRA0qqN8bYG2U5v8thClCeSdaBXDb,iv:Bpo35NRvZYf2ydofwUdDoa8pNimR9BUkJZVc78UHuHQ=,tag:/gQ7iGcFM6g3xbYVIczUpA==,type:comment]
    #ENC[AES256_GCM,data:DTbFDhkBO4qfOJ8wERZuRFhBuEyz,iv:QS7Xo3fhvXSe1J+qh7bdg/wLBJ4q5Y8kXzPlbmOYcQ8=,tag:k+kL55U4k5UnalUZNz2ZDg==,type:comment]
    #ENC[AES256_GCM,data:mQIaaBK/oCXNRDHqkv2QmRhN8X6kc4ps,iv:9iSY2VQTd6meDpIKYknwWnkN+53QccnwalvJq0am2Ac=,tag:RWp3JLi7kTcLpBAOB34zEQ==,type:comment]
    #ENC[AES256_GCM,data:RyQPHvcz7tJZ8bp+NdZH9yvlnPKVgaXU8vG304p9WdZ2kQV95ejeCTnZ9PY5KtmNxCk=,iv:KigFlSnbh4S/iAg/PDEMWamNMvh7kwEPXWcAMkOdQdA=,tag:FfcjHIaIMCdZecUVTqY4fQ==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:ojA+eTy2dttCBzStxsx/3UMEfCB5fXERYrJmmtZJccAQEDoMAUOdSFSiE1zizfB3S1HEI/1vuZplHh8g2SH+bw==,iv:vFfQOhjEhl+fEFjHij8sJUiTN0dNAgR8fKMQEZ2GdTI=,tag:OexAX87z/xrvMDkJFBKiuQ==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:JaTsKkoysJggOSs3nq0IMnzxwhYB9MB82N7wyTCobhe7Gg3DMMHzcrR3L+NYuPi3wvKT3/jIux62IUwi0/N53BmVEQ==,iv:2TwZrtHFQvBFtuBfO9XDWBnt5OgVIKPJE030A4tMnQo=,tag:R8OXZUIrUmeGF9jVc+f6JA==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:5AhIWT/1deqDWzWtrCZnejm+zGZHs+VUzNk8La+4NU2qrY7dYCjWAWlpv0snYpwcaEEc9x5LDmpQ4b+/6MrtZWkGtxdxWQ==,iv:0yt3MXKbtz6mkRUg75N5+Qimd5NExw6aIZbdCpthd8I=,tag:pQgQgIeTWhxDvz1V1tZ61A==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:QCHNF7jk7vE8dorMQxMFdscTbIRGonorobmnUZMTVBcDLQqceVJghym4j6eTJE9jVms4DMg=,iv:ti+23PbHZeQX67zKAifY/yNHYg1EmO1W5BfHokTUSa8=,tag:82SumRB8HVioCTPHxKt8Qg==,type:str]
            - ENC[AES256_GCM,data:6EvubJKqYYpg3FVm2vvaPPIT2L4SaOsg3tzMDzOJVH7rOdSkt7o7CDDvn6fqJy0ct2PaDw==,iv:f3RoMRbNi2MGWZ7cOJpfV7frqZx0OTbbBNeeaewzoKo=,tag:Zm7bSTYb0IpqfTNJJEuT7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTnpCMi9Fbjh2bllyU3FE
            NmJQQmUyMzdMYWs0Tk1XdVUzMXBxbjJRc0F3Cit1Q0xld0tsbnBxdkFQWmVNem9w
            MHdCNGtSazdFS2NJdGZWK0Y4OFlyZmsKLS0tIGpDRll3NzNIOSt4dk5jdGdldFlh
            WDM0bGhxNlBibkVtbmhjY1FwVEhqdm8KzXFyLB/0xw/Y/Lu0CdEhJITb2cDjQpCG
            leKRMVN0n759m/29uBhlth5cA4w1qPSnRYSTqDk4n9KXpqPtKtBjTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWktzMDhZUzhTQitVUUl5
            ODJCNGVzc2lVaVN2R3M2Nk5uajNoU0htVHl3CmZxclNScEZ1S1hVckNEaWdXSUgv
            SEloeTJoclVrWi82UmpIS0l4R1V5RE0KLS0tIHFIK1NjelhuaVVhRVhOc3l4eVZr
            Z1MwcVJacThRbGg4QWhzK2JkMXVMaDQKhzXKdcscoziXvkFa/pz2hcmlAAQcnh2L
            2KdpzXXnSUhW8vYIpBomhn/A6F8yTxyEYumvJXAc1Gj+vwVgSEW0Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T14:52:23Z"
    mac: ENC[AES256_GCM,data:seTBHlEN9e8usDQi6fLipcBr1Un+m1OritNci4E+9A67e9NCLB21sWeCsMa/B+qdqQpDyfgVLBrxEJ+BBUQjxQnRlTLapCxqHKdzP+dvpVmPQJugt5ZmNmG/gSh+BNxiPPAkr3ZeQoKuhHdeLl6BYkP26f5lhR60QL8TaOs0Ycc=,iv:76JM129VSGakVxzvvft7ZHn+8/viydeU3r4s1RO3P08=,tag:cAHBNrrEgDN2g5JJPCNs8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
