service:
    #ENC[AES256_GCM,data:YjzOOBw/o7ZBMbUvcmYLBaSFpj6D,iv:nDqbbDa0WNV6Ab69VqA0DO6ka0Hr33MOSt9kyn1zZmg=,tag:amJT/3tlrgQuZt65ShilCg==,type:comment]
    #ENC[AES256_GCM,data:nBNiOQYNEnM+4NJU,iv:IT9kxisAle1kBBUbx8EC7VSWQ7oJxt23qDMGGZQkXkA=,tag:GyjGdaFR+XelVazGded71w==,type:comment]
    #ENC[AES256_GCM,data:+diaIIjfNQX0IAFZ+AU3Ec5n0RTj,iv:DO2Bc9G0Q9R/okSesWOmXYtBVKfi+4SZQ5G0OS7upc0=,tag:T2xV0zEC4oc21uCqtsQCcg==,type:comment]
    #ENC[AES256_GCM,data:nbFtPjp56ddFx7nhT4T+DvWPS3bPyziQKw==,iv:wmRTNOSOR6yK0CJCJ1WCCRcuf7xftktL5MhkGTU2Rt4=,tag:1b17ZYJ7fkwKGoLFcO24EA==,type:comment]
    #ENC[AES256_GCM,data:4Dsrj+oHn+Z42UdqpgBSKB5BtCD8sq3HCU9f6TNdpvkeQobsPM/vR8KIMXQAUH/i5hYx,iv:WVytxxhlUmvsgglOjWvzsTWhecL+ag3fIZgwGja0CYA=,tag:HnYqZKGWp24EainJh09yHQ==,type:comment]
    #ENC[AES256_GCM,data:oTHJDNpS0gXPFIZb0mUaLnkR2ixH,iv:CKnrUOaJ2ZQefgdHMaHYWF41UE9s3BKx8sKC9XcuQGU=,tag:qiELexgXuVC+8m9CAJ0uzQ==,type:comment]
    #ENC[AES256_GCM,data:Gj5iN3uNW7F/5nl2cm6WJ8/YXUFKcRtp,iv:IqYgDsGUgod8bEuwyjoClsrV1OI9sReo0UzAGbrGb8Y=,tag:fEzIMyfae3inEgWrs9MQrw==,type:comment]
    #ENC[AES256_GCM,data:A5/uQherlYPGpHv3RewBPevKxfCvZWgx1qb2O3oxrb6f/+Rif8Nvxift50Gvpfhg9ec=,iv:dy9nTsNc/cNsjPkGnlMPtwq9yFSecBglwTiCPx587Lg=,tag:t3YdirPHOWTno8hs65Kv3w==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:XgijDag1lbFLHOG0cycTgJbnQFFEPgo9Ba6vUYhzCkhPLC9RlnRhRNt5itmPK8eaasRzG7605HEZYyfd62op6w==,iv:LSqhsmLwq4Z5jh7QF0HISXPUpvbgb988h+9t95ZFr+A=,tag:VKK9Nx60Kwfd/Yd75AA48A==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:ZWUVoCv0T+hSuKztqv6f+XGA/HZM5yNA52hp9YD/PLEw6Kxmlc8veaQaTzeUPT8M27eBEAgSqzUWJehBelyWf9Vy6g==,iv:xH7Kzu1gWfwLO88cpJ20yX2jiGqfYe1jsLI2QDdno04=,tag:RAOOuXHVSHjNf/E7iRO/ew==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:rYnFMQbQ+3BhGhJyDvmSg5Kz96NImy4wLh6T15YDRvyWPx7csdPbQCe42gidMn07GcJFiGo5NH3xZQBOekkCD2NO12VbtQ==,iv:TKk+dwarjMUpWq4mTG4PpDMWiOWLTIBf4+ZjTwfZFnI=,tag:us5A0CqddK0pQZGhdKoYAw==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:0AJpIbOk2yjhypP1lXHqv1OBVw==,iv:zfSet57Q28qzlZNfnIoCzWZpCJiHuHqxYV7vFdBfmyU=,tag:EoUvzOoSUrjAmJRoRcSbAQ==,type:comment]
#ENC[AES256_GCM,data:dAt0NJqQI/P9UT9I,iv:fj6dcR4Wuw47XR2chRcnM/ceSc/LIPbfPcdGem0h1oI=,tag:9XptK51zBqTgNjStlCdSsQ==,type:comment]
#ENC[AES256_GCM,data:3rygZuy3GI30tKurOiGFM4Qs0rhx3QryhIvBWMzcpwuMvwWN9KfUfebYXrvEZ0n5LXdEB4cytsDN5V6eooXIRA==,iv:ALCorgOkPJ7yWLNfavCZhORIpzjz+Up6qUzw+Tgw0dw=,tag:b71isX7RWs5LknsdeYxd9w==,type:comment]
#ENC[AES256_GCM,data:d3n5V1Re5hhvCN3KUvPB8fRMGPEe4k0bxaP6YvTLD0RQ/nor7rqfa/qshkK30N1ub5AKWne3SXP6wF3cRKUx,iv:BCylZ5h1cg+KOGci40g2BP2npzfl/6sG+HLfCJK/XWI=,tag:Mw2RuyG5SxmwjCka3FsKrA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUG9jSWoxc042RDU1UXhH
            T003VkpYZEJPWGNtbnNBYlFtWEJxRDFsWFFZClJQZjFCMUxtWFJFcGcxL1ZHeXJT
            a09aZGhIMTc5SE0zN2JOY2NCSVJ3N2cKLS0tIEc2RERWZFZWYWt3UzBuTEliQzc3
            MUpmTSsrcGVIL3BMcDl5OVhXVXZtY00KVrkUgeM8SZwJ14OccBKjsDGPf8Zn0YkD
            fIfrj9OFyqnq5s+MKY6LRSswYxVDAmblAsPDZgrI3gMTh1OFYD5GDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YzZ6aTdjM2hneTA2UFY0
            V0R3ZHVxSEJPUDd6azJYRitJWkkzZXl1VVJjClZwbEF4UG1DVG13ekRIT1g2OWFP
            NWxHTTB2UHZ5bFlsVS92aU9QSHRDSzAKLS0tIHdYOG8vTi9veldqNUFnUUpDVFdX
            ZEJmS3RNZW1GQmlmcGVvN2hRVytaT2MKunyiJNXdDeYqctRC2nExqfZ2+L8NCNKC
            Dq5a8Ys+GyI2DAljDnsyUQ/vPuYkpqejl7/XtE/Qu7ozX/88gZuWxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T17:15:02Z"
    mac: ENC[AES256_GCM,data:Noq2+3oJGSw0xkaTx2lQ1u0frmE2unzF4/1SxHxukokdeOMAK5/h8VPSLcnLuKbD/jYn7f6ErLstedwyyp1J8FydBY7+vwnGJt8Io3x7L8hOX/VxLwbeppRncPgNiWb+VIBzNWoaCxrUS/kU994FlKNW/52tih8qDXdrI5KLzzo=,iv:LESE4E/Mrl5dJcvE01j9Wr0TXWaT3D653xeEIkvqVuc=,tag:f3SLvdo/D2bBOK2obbQjpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
