service:
    #ENC[AES256_GCM,data:3HVH+aE/7DtUCtTt7HrXddve2jfS,iv:GkoLlfqaL64g6aYAkrVbCSI4lviYfn4oyjEB1yxiHzM=,tag:fXFQq934NVjq5opJ2DYwNQ==,type:comment]
    #ENC[AES256_GCM,data:hOpGFCb4ljSYEbzG,iv:UZf43Wf5OXgGRqItfg5QPzdCKeHqgf/zJDc3n/VqqSU=,tag:DuMO/UmDJRMnEzHMKgZ7bQ==,type:comment]
    #ENC[AES256_GCM,data:dh1icn5BGra5FlkxXZMyReEcHI42,iv:r3hTtnQmXCk5aC6LiiKSl3ahNqB074K08ypAPNmwpLE=,tag:DEo5vsBIXN62/+/h2STH2w==,type:comment]
    #ENC[AES256_GCM,data:sMIJbjKJJEDY6W/wUVd9sz4nud+xBG1qHA==,iv:I6BL/akJ2rK89PlDc9OYhvhcMqTVZLnkUGeDyT8Ssf0=,tag:tZlu9gDVrSr+eGVwQHkk+w==,type:comment]
    #ENC[AES256_GCM,data:tQochzoBJMOGQeHBymBV98yIrhGOZ+mvUUiEOfDARZj50jDKS4cQwAyKnaePhJadAfuZ,iv:7vqhXBsldqrmUx9cIk8wlJZ6E55of0vQU2p5OqFkXm8=,tag:gzi+eSZvhGLe575n4ji2Hg==,type:comment]
    #ENC[AES256_GCM,data:6n0OZMnhuQl3H91M8PCbgYZ3a+0P,iv:MInv+mQMZecU37JyvUHuly3217T2huV75EOi+o9Dm3k=,tag:LNMzkgBDzcUlvYAE240PiA==,type:comment]
    #ENC[AES256_GCM,data:a1HAnIEMoelVPGrqDRRTkzUB6IWOgpf8,iv:kPUKfAZLcHMuMH7iJBSajc0YL4eJFfJ7HOUec2Z7u5g=,tag:8ivX1QfbCk/Q+FC92WIx3w==,type:comment]
    #ENC[AES256_GCM,data:DIbTuHiSgleW98x/cZloeZwoLYUiWCLl5kVrceFcWBVtxAqZo1xnx3Tpc0SvpNR53bw=,iv:dj9d4CDQASIOC9/EY6LbBnv0xgKwX2gseiZYPcCTe1M=,tag:8uez2cs3SJ3mnxVJMe8B4Q==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:++QEy4GLf7RyeCaQr/1Q5PZNnDZG/V5O68HLzdrhN2iMhpGld9UwVTqmZIAApbGWVSqsCZM6IPkwehTopVNMMg==,iv:ohmLMTR2pdBtd4lJx3kSXpFaGUZu466dYJ3wBjsKdNk=,tag:QXA0UEYUhDkfPqPWGM4pRg==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:NDqVoEGb9cYi63KXapL+DiWglG8u6oI9vDot7/oYrYokGuaBwyjL9KjV059Hujolu1LiqJ3qUQ4k+eDMRdXssX9yyA==,iv:0iLeFWWh6p/HtiYfkC5ZmOcqKpfvi3NjuZL9dKu+XnQ=,tag:XFC9dWJnTKx8XHKxKI/q1g==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:OQ/3gNEk70Y4WIFY5G2tFDtln/CImuOc4XovPWksvKMw2tQBkYuFrPRaDwSXcnbotyP0iO0S4zyqJ76EVpmi2sbWmtgpUw==,iv:uB+dGRyt3W4DLnOy8dcxwGI9dkuCt6Lt6nJbQZnNsEk=,tag:m+EPf4xjjTqe2W+5k2j+Cg==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:9NTuoO+fuSjj3kXdDR/CSmNlUA==,iv:7dqaFXbPANeFgEDKdN7OVHH4dJXIFVrTMpHMj+svUxg=,tag:4aTZG0nO2VXoDXf1hfKaRg==,type:comment]
#ENC[AES256_GCM,data:xkEixlwsVTKuYHnT,iv:oTL3SwkBznQfcC6OYb4mZ9IQasXb8Iu7cfJgSlMX5rU=,tag:jnvPe/tzNnqKAbKC4M5LXg==,type:comment]
#ENC[AES256_GCM,data:WbHakn/vke5vbOi8ZErUggIWCPCozgcloEQfN1NtoFT55NiRdwgyN836YT2OkKyUfhGcKmiRmwALx0FNefK43A==,iv:eDi6z2v3ave7xvGbU4Z6dYIyqkygTUPYxgOmirQTWPM=,tag:TMSQE9IaaI2E/zMQFwYyqw==,type:comment]
#ENC[AES256_GCM,data:/E7pW4FzXIDehzK/8ixAedbrYNE0U+P0AsQcR1Q3HlirvwLlg5f3Uugespo4iBl++b4EZPZ83wXhXqw+P3bc,iv:NVrNRbxsGPEwQhI2Pzx7or8U5nzwN0cnjGzc1FN3gdc=,tag:xF37bUIUpp22zfB8zb21gw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnajhQZ1lWbmhFeEVSYVFj
            alNjVUFIR3hBeTNscERwV0ZGNkFqSExiUmpzCmR1WUdNeTFBWkpURzhRUisrOTAy
            Q0MrSWFhTmRiQmhDVEJNK0NIdm54TlUKLS0tIEV2dHJCdHNaQlB2a3Qvbzhob2ln
            c2JmQjV2ejlWV1J5cmwrdEhSS0JDUW8KPBE60atssZslmIaiZc1vw42W5atBN5a0
            ikRQX0X11d71d48DqEfdbWq7rXxb0/HB2CBHSJv3imub4ze5O01vLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOGs3cnF2WE95MzBvd2Za
            MFByY1RYa1RSbXRyS3VtN3ZrOGdkRVZDa0NnCldNeStCbUIzc0h5bmY5eXZ6U0tV
            RlZoYzM5eWZZNStSaW9TNTBxSnhBTGcKLS0tIDZyRDhvdUUyc3h2dkNTVCtRcTZ0
            QXhkbnpKVHczKzhLckRVR2JwaGNoM0UKAZLMSvJ+31wAAG/HWR4rVAbU57mYtJAx
            U0SnyK04WjT/VeH5qJmD3OjAoAk2zDEEqFkF7Vd6aOlJi14wc1s7uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-18T00:02:03Z"
    mac: ENC[AES256_GCM,data:abf0a3oAITgvtgaXcCGVoie7zCNVa1VPs1OjKiOTGQ65kPILI7sHfIRpwfYlqDhOXCb+4XhoTtNZfHFxQDp9EgtWxmI/UBoBxFGZTT8WSLz/C41yRIBZgQaNTpDRJmpRcVD/VxXr/5mPuR0zBXdkPSuUR07IZDbZ+imNjnzBcME=,iv:4nGEAj7huJfYgfo4o68LBN9JKdxUNnx40Oq7i72FlIM=,tag:CfBepfLmqJ6pD4S3fwwS9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
