service:
    #ENC[AES256_GCM,data:RytdQMnmGECSDu0/HCMmimryDF1J,iv:diEiYMC5ZP6llzrh5Oz304I5lLZl8gHFFd9Zckbocuc=,tag:brhawS7N6fAzRo+2ReI+MA==,type:comment]
    #ENC[AES256_GCM,data:2VllJN4vLSnYwhER,iv:aKORT7f09b7oxqyT96HEMDf4Mb3cD1SK1a86mq/2QR4=,tag:prNXnGI8+wjqKgrW1GVsrg==,type:comment]
    #ENC[AES256_GCM,data:prJTM6kWgGkpzIPj0qQ2qyEgcYeY,iv:Vi+ZtVHNORe2PjvH08TqJhnun7KhyE+gex08AlouWoQ=,tag:BcyPAxrmJkcs3taNick+Kg==,type:comment]
    #ENC[AES256_GCM,data:KInC7QNKw4rDRmGjnhRHeNSk0WKVJOhWtg==,iv:AUoydZuKWeCAFfq3i1pgZvMGF+e3s0G8mS1IjNrbVqA=,tag:ZgUo8Wk6XvJlB43t5KI/ng==,type:comment]
    #ENC[AES256_GCM,data:AHVWWWgJAkNAbBST09J6ceBAN2J77MEe/YM1P7jjM5LOGt1r57r0w1obP5wnD6pBZRQM,iv:lzX+U2amETvvDb34sXsPZHj8WvVfiKJmImz0sUHG1Zo=,tag:ITEE0tIHedQjE3iNrMXGcw==,type:comment]
    #ENC[AES256_GCM,data:r0E6DUF7iOKkOr0H+eDmn+/jnXWM,iv:41v6AtrYdig6KJsNSfRqteuxf+fH0PllssoBApo6Ueg=,tag:xiRGyOC9XI9xnt0SezZ95g==,type:comment]
    #ENC[AES256_GCM,data:ZG2pC0e3/6Iy4JJmRVP0nnTPw/3TDq+V,iv:dKsTrZYR88ShcP0GAL08ryauaPrfMSZpMjiaIF5VShc=,tag:9XyII3Bj8uvmHy5tCY2kWw==,type:comment]
    #ENC[AES256_GCM,data:1fcYjzcv2nS2VtOXpyJeEK/sxsugNIblMZqjqepuh7OJ+wmP5oSwvqaLTS6OIkpy3W8=,iv:sqhpCifXWXlcn6y+3LCH777UucjTqwZeEECowk0GmDg=,tag:WGikBzAoJV9j5+yPEpE7xg==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:jjOgGI4BxVwpsx8wWOuOcSHuyttp56+WjXOK4UiIYPMs0Nrp0Nh3+HqUuojNl8IPyJda4lNJMKQisdwgRMkxmA==,iv:HLLqBk+MuyVkVlTVXr+Sb7sDm/TZSV37wi+8jngcFKU=,tag:rnQtP0yDFbkQhLf9i84GXQ==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:kEU3yVzutY11luAZlOTbHwGayaD84k0Ys8GnX9g7dX1l1ignwU5mCXha4mmLFiGw9tZoODZF0OFOxmAMPxsk/poyrg==,iv:qr2Cs/lT3PKw/D5qvUzYYg1trTXmnqhLnZA/k8jUzh0=,tag:0h+iFZrSd0us2mpm5NtckA==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:WpuA3ANhAGHUJkCcKb9Xjzdxm7z2WQBaITMVWNHko0SdAH+W7wtIN5EvCVl9tUIqxMUWogEhkic6ddGX5mWlFbnE6AKLnw==,iv:wS4FD3LbwNWhFKM1NcA8vojh6fu2cguxr5y89aKTj20=,tag:8Qj474PpEYGJOgSAheXlNg==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:fwavc6uMhmcUVdgHi7lWU8pqfQ==,iv:n4cc031gwUEJ1N9vfs8xYfx7tz6q2OK7dKbP/yZOfsk=,tag:6maNKOeDuZW5A9f+L+xsNQ==,type:comment]
#ENC[AES256_GCM,data:wHNy/P21m2E3EdtG,iv:7kCGhiDkdkeH8FNaNfxAAl6IUOaq5qqylCV5EowTXn0=,tag:dQFvLbP7TLG56NMNBXJAzA==,type:comment]
#ENC[AES256_GCM,data:G5ol93Nt0v5mjY3E4qYd2aHpUfjPFOy+YPQuqU7dRUu9xvpnYGp5auycG+RIuBJZQV+4ZST7ROuOqCCjAyNA6g==,iv:1LHP1ZeNJgIWNeLz4Nd8/7ZSHLbcYHoDzDt8+5pt/b0=,tag:E+8HwQKp34RR1mGM7+gkag==,type:comment]
#ENC[AES256_GCM,data:EK8PKPrn5qWsnpeuSBkuA61XkjycGZxThNd//U/b/RWoj9bRd04mcjReqlNTEhS5edexxo9kiiKtKxW2w/fP,iv:RpsAd0s5JR2av7Eukn5v6FTeo6gQV0618ApRoO8dUAE=,tag:SHAXcJAfZIaCYVROCI9hBQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL0JoSll3WEo2WTFIOHFI
            VW9WdVBPZjk5YmpkSFk0MkZhbFgyVm92MkNJClIzbW9XVHNoNVpKdUVKSTRwS3pi
            QnJUVXR2UFQyVERZTnd3RksyaUVCSkUKLS0tIEVjbi9UNzdxVmJ4aDBvajJleVkx
            eEVuS0xMNmJKL05zVzZzRDJsNUFhakkKjGOVdmsmmGFy/VjfDaNnzGCoOzXxjX1j
            JOurhK6iYPRjxMhp5N3PBRvyPn9F6rsx9JOB9YQ7pgcSmmdcogcW6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArN1ltN080dTNTR0RKVnNl
            VVhkeTBlaVVPWG90K1k4WGlkU21RWk1pQWlBCk5kK1pGN2FvWDh1MGJXRWkvd3Ni
            aHNvek5pdm95UWV2V2NtQUdSMDJSV2MKLS0tIDN6Z0tUMXNOcG5sQ2hXc05DdFdI
            T1JBZzFlVi96eTJFZzBKeVpyc2dxL0UK+pTVqUb59tH10MTR3U45gu8lG8a8DqZZ
            v3LxTohbCAvnPX2CUjsmG75DsIZbfrqT7IQ9nkqjft01S060UDMrHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T12:23:17Z"
    mac: ENC[AES256_GCM,data:0H18FpVqxbIfuSz1z3RMVnIjw9R3mRpePMExsdWl7vy4wJJ3zxOsnVmI4tyQtPQp8LtY1jU4Dv6CXpZ4R8wjEfzfZwr7d7uAbUspULIwPlSh3ioLf73dUX1tW/UMIjFlO+S29JxVsS6wGbSdJdzJVNTwF3WlYTpaFcF1BhHXp0s=,iv:WNgOWWPvqm0L10E0c5zNEc6ntExNB7nY0jKw2Piyjz8=,tag:h1/wdw2VmjOcVsKkxoBb2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
