service:
    #ENC[AES256_GCM,data:6loW9mv8+yfhbwWuAl3d0xDzGXNF,iv:L/HsJC/eezh7xpnU+dE9PRV8nN7aiV8MA91Ncdh6Hcc=,tag:k+xeHmIPrlJMM0qwqyiD/A==,type:comment]
    #ENC[AES256_GCM,data:1Mr9rB9bTA+XCW/L,iv:MvFlaHuh70dKt/Kqj8hmZUJnMJ0dzY3dSf7F57t0e3M=,tag:puo0Lw9PRz2wjQ6WYqG+3A==,type:comment]
    #ENC[AES256_GCM,data:k8vjwK1ztmRpPUlTg0Q8S4WQNIRg,iv:/5eZGG5S2mR2/FdyL0gbL/tkLH5gUtcp85kjsidgueM=,tag:kI3//39y68XA/uVcHHgdLQ==,type:comment]
    #ENC[AES256_GCM,data:ikavquaDkKPNceLFnUHc5hclo2DnU+D7Og==,iv:eSjppJ42ByCIh1E5vkZ1Y2XfJQX123DHKvc8GjIA40o=,tag:VcaSJvh0EA/qDzrzIo2Z5g==,type:comment]
    #ENC[AES256_GCM,data:2Ph8ULQAMv8UP8pS6jmPAZFN/d5yHd+55Wa5syP/3WigVWuMYeSAkEIdSJIBhQFJZMnv,iv:B92Xe9eH3iyGP0US7f8yeFhk5BsIAxnATx/o5M5fARg=,tag:71Y4rDg/x7B81UYth5bglQ==,type:comment]
    #ENC[AES256_GCM,data:egP1bhh/zDzdzQTtb8v6g0C3uy2l,iv:cWo1PYQWu0XJULnnrGY1M474ziPc8Wyv7ahSlmSNCGo=,tag:iCnICvPmQ2diWeA8bNUdVg==,type:comment]
    #ENC[AES256_GCM,data:rsjUGJ9C4meemgIiF0zZeVN1Vd/l03US,iv:CjxaGE6WJk3oEq8YnqlnBIR8iDXmD8v5dd2y2NEUaLI=,tag:R8CC57J6ITy1+NgX/B9u2w==,type:comment]
    #ENC[AES256_GCM,data:c2JaIUjrGltI321cQijoFAdO34HrurUPqT9J04/2W0PyhNNKCr2zqWx/9GfUAbnp2WM=,iv:zbSyxW83UC4BJRzp8N+7nb9iTD6npVPwsqsge0V6hfI=,tag:tdhFwNG6ZZC6fu5qHzvomg==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:Z4xFKs/28XDria1CbQ/2URwgqSMMKg+kn99+o7BexGL3j+ehn3CG66XKHECHVcPSBtDaWhOXzz8/xnzhmWPCzg==,iv:hHjnaE1Ct/JZ1Bi3Y5QHPb74umbnTOJDjOvfc5WSQ8I=,tag:+EZPcRed3b4ezK+7DuFosw==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:Ah2ylhaPQaog2u3kU3aGwQAW7tcE1db/PpFyqsRpWX+meJeZAvlSu6vOV74Q6zYBYQWFXxsqH9pftH2W/s5i+G6Drw1DMw==,iv:j9Tct56UNPnKZ085U4I0Wfzt03G2TSsAxUFpgMgNCA8=,tag:ftKXLhGp6eCXKV2aWpCqQg==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:kn/fiJ1Rk4XdcKUyAkjzjpeD+w==,iv:l1+julhqwe1iPJ8APQq7DR/TIfWwQ7fskHxPejJfuPc=,tag:GEdWqju+SuKZx+FIjutoRQ==,type:comment]
#ENC[AES256_GCM,data:zikj/V4MgA+NnaQM,iv:/noCUy01r99blOhPTfhNRA0ashLLqZJ4ghdli0zcEhc=,tag:lGFEy6g49ygB9WOcD3Qpkw==,type:comment]
#ENC[AES256_GCM,data:3eL9owunyD1+tHUeK7wTvIszFZ+HrG9dGcEFeoH+b5kQedtU0EhZR5KZhy/WcAouUHnaMh1ai2AaKhBaUtvZjg==,iv:BkUeGjMSp6Nk4kNULAUcfSGMC05R6up/NiyyV62bJgE=,tag:xtsteuZ85jPrJzr0dfhYOg==,type:comment]
#ENC[AES256_GCM,data:G2TD+ZHTiNqE8RcnKs2a70Z+6ZnrX0qzEAcv2Ikjr4gI7tkcogIOaLmOtl2rTkUgYufCLrb1VbPt0fqD4/us,iv:kuGKg3yE2HfucvI7Re8d0zRe6A9Kt8AIa7SXUy+57wM=,tag:08z+xs2bkrMifiJm0f5CVw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRnF4TG1sRTBzSm1YUXpx
            WERpY00vNEJzMks0OW93d1ZsU21QcUNOWWdrCmRJd25OcjJYVG95OUZScXJrakZ4
            clA4QWp6QzB3SitleDMwWjVYWEwvTGsKLS0tIGc3bStmcTAybHpPcWhrQWJmczNI
            ZmIxZUxFTXFLM3JYVmxWOWliWDlMUGcKjmcIFM+PJiRjKkN0gjltZlvgbrzEeA2J
            +Y6SjxPVgy/8A5Gv6bFe/botacjJAHWkzmbbDzWVl6OqAQx12zH75g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UHBHRlFHbWtET290a1NF
            b0VTOVgxTS9iMnJzU1BqTDhPQjVzTmlWOFRvCnBhS0Y5bkkzNko1UG5qbzlaMERU
            Q0MzSWd2RmFQOXdEMDdjbEFUS2R5T0UKLS0tIDJDQUFRdldDTlBrcGRuWWdYV2ZL
            a0JONVJ1Mzc0TFg3MDBJcnUzV05uRVUKW3r4nWdaLb90CVUswuTccMjwSDYPCj/t
            mvF7ayv46QjUcUqA4ipfsnuQSi0YRJEuXXUReLpsaPf9gu3hDXY55w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T11:39:56Z"
    mac: ENC[AES256_GCM,data:4RQ4Zvt/IttBcnhBLY3uQ98mA0kmkDGFuHP/osIrMuI39PP2QaLfkvB1aOrly5pTkX3hU9Nfj7LER/IocBbJJQ18z5XWiqLYlkZneu3cQq8Qvy1VGsE7fjoSr7WlqUZejqGExalEoFMJIcjCmW+1bfqdP99G6oy8B2V07dXw1gU=,iv:b6srGXUcSzHbHM35mQONHOKjsuiWnFgbWj6fwx9FcxA=,tag:qrBNy4qfOKYwuju8Wq0PUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
