service:
    #ENC[AES256_GCM,data:lyo80XsWbfOTFZF/cNsDahN01qo5,iv:ywi0lKMgK1lZ/p1hmf/xMNgl+1YgCiRqo9T3X96KiCc=,tag:9+kJQ3E0GtbtrY+jYtYpsw==,type:comment]
    #ENC[AES256_GCM,data:kz5PGTxyNVxZAt3j,iv:sO1SXk4X6hdNFr5OQxeMIR7eqU18iTaa+ph19HrXaFM=,tag:al3zsTLT8CRQtntTth2dQA==,type:comment]
    #ENC[AES256_GCM,data:cAM+GyVpSZieKvNm4y3xDcsaW75d,iv:O1PHViYtPIce7M1K6koXipETA6BIbsRwfqtsFmzak34=,tag:BAeVZTBpg7R2j4DoV+kUJw==,type:comment]
    #ENC[AES256_GCM,data:GtobPDfsusHxONFhpy3i4lQq84sfSqjaAA==,iv:M5nHqCdEChVXIzTeqLEF0tCcKKQWSLIE4P3dFoeZ0QE=,tag:vdWFt6ShJdsWoeulCPt9wQ==,type:comment]
    #ENC[AES256_GCM,data:c/l06nCWZZVaF9jjaXvZP56gAKsdk9tUULlFNQ79g1trwMqxwP2pg/Hzre8w0InULYkg,iv:oka5q6TC5m4thmRJf6+VFSuCI/5xc0QQYPGO4LdQyTc=,tag:Fe6I72URA/u0UT00GxzbBg==,type:comment]
    #ENC[AES256_GCM,data:IY+CJYxawoBZEeZJQTrLKbkkIqy0,iv:U2l/c8woT50eZbcpEE3q+gC1fw/rHJscJwTJp8pvsoU=,tag:D8uG6E6TNrPoJAqT8qoGOw==,type:comment]
    #ENC[AES256_GCM,data:DYi6bewWw/Ovs+HqUWhSG+jY61XcYnUj,iv:ySGJNpc+ngC26QMowfCCJ24MndSHOXPgZau7xlNMpmw=,tag:VDLtZcwwZH9fRim61XujKw==,type:comment]
    #ENC[AES256_GCM,data:qAPPpUyAcZh5FoKNhFwVcPgmLkqIaq19qYgmhweRwbUuWiQEkE6X0F7pAIw9Q03MOqc=,iv:S62vSa5y1TaH9F+gnD3l4uWISI7eXpPO6b+kGps4O+8=,tag:74o3KgaYV042pVo3ezhS/g==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:TJpEnL8jqOzWRGhj4WDkxc6OK7mfEzK/WPON9qyx9vGdAuud9x67pFMd9rALYOsa5G1pO1SW7CpNPCdlxGSKVw==,iv:shnSP2nsB39iI9FI+5XKdya1VUpUP09Tx5YdwCOQfK0=,tag:Za1/txepggzpnP8+VdTxPg==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:HYX5gOccTYmdLCeE9/0edb37kwtUCt7x43RP3HDWzpvuS29fApfmglXDNpnGBgC5PnKQffXWdz/YcsH5KvpAGNfP8aoIEg==,iv:vx5BGZgS9TwoaCwgHL6mI8jsFEducl8PDnOIf1Li1Vo=,tag:DltlQS5DGHypIdEZVMk5HQ==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:ruVhJO7GwK/pYsQlZpAz6o7b8Q==,iv:ycbV8+THalP3CCqlGYmBgR3YTtdUfsjaoX+3PXHi7/o=,tag:6onQXyOlE/RnoxF4ZJRdCQ==,type:comment]
#ENC[AES256_GCM,data:xXdiooT54alYJwQW,iv:hHcjjXR4h83z85rVVrZ0a8xzdhgIoUYHf+Ww183Lk7o=,tag:9VxpdijL/Ov3ZsJ/7c98rA==,type:comment]
#ENC[AES256_GCM,data:WRYV/fX7kjJOq39bQOJlQXVxeGjjlhaGfyVv6izy+kc27gXQhKnMLwLivTuXsw4O6Jh9rhcxVPhWoauNLvGGHw==,iv:SoJsJaKig3XHz2GAuhm0R7qbcplOPOEra5oRH7cBLM8=,tag:bZwSn4QHGzU1nbdWVkWloQ==,type:comment]
#ENC[AES256_GCM,data:sc0kxEqnBmkoDKwRoiA12guZxnLh+ggHIpY830hJuxmVQkx5Cz1dJJa/ZCN1+FIoSU7FeUCDHFFT/4BuLYiI,iv:MLPi6KFxZrGDbVqjtBd4q9lt13Q0mTOnf5S/OfnpQjc=,tag:vOzPE8qjHkCgMNNg0IfsnQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc3B6RFh0ZEp4bEMvM3hR
            SWo3SnpGcHdiZGE3NzBCVmhUVXJ4elk1Qmx3CjB0b3N5cEhQMU5OZ1RTL0lyK3lZ
            MExGM2dNdGFBclVoYUF4VVF6UEFDODgKLS0tIENqdGwyblVQR1duQU8zdUYwNFNi
            K1ZITGNDRitWTG93R3E4bVIyay9uTXMKBDqc7Dxa3xdJcWhhDUAyrtwUMZ5TWHj1
            mMwJ1RBEf6XWNGcqH9JMj6kOTeWTc3UR0lV6TppWTJxUrLneTSqIow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVJ3T0w3NXRhTndEQzdZ
            TEdZWEt5RGhDdVN2cncrTkI3S0hOcnZTemhRCkNTUytFZWFrQmJwUGVHWC84Ujk5
            UGRLc2lEM0VKd3BJMUl0ckRWTjVDSk0KLS0tIDg0T0ZQbkYzSTg0aDBBUUYvZjVN
            NjBzbVpuUGc0bCtqaTh5TGJZSjNJMDAKcHJDgQJ6xAWm6eDnaNnbY66oY5TO5O4I
            NCXhrn/L9KwuOdttbMiYYG0RGFWkgWXwIjaTWMuKC8Db+tvsstkM2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-12T09:51:12Z"
    mac: ENC[AES256_GCM,data:dlCm6d5P1CWyOkkuI77lAPmcdUhzSSWEDTXaDObaTOH8qi0BCCp8ULCZq7gJPt6ngVw9GvDWDy/GITBaWIKHoo0caz4pbHXU7jc+y8bWziwxfVU/sCOTDlEDEXRlG9DFSjqh5f23DlFpp0z1ZSGvRQtPYLqwLE9/VwllX2F981g=,iv:U4daoa5qCryR4T23EhR7CGiTNYJWQeLF7J70MdCBVWE=,tag:Vc5Uu/G4wKAGGd/xZFjStg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
