service:
    #ENC[AES256_GCM,data:onaQ+Sf/Kcd+g00Rur95B7zEJkzJ,iv:urYPIAJ8Xqx5c92BYSXK0YAHcpYFOYpCRY1+JIq25GE=,tag:ttl15d10iGf8CsoIF6hEyw==,type:comment]
    #ENC[AES256_GCM,data:wjgdr67K7qR1RGzM,iv:Bh+gdQbnyZspi9qHdsHJXAxENhtOwQS09f8sYWe8/hE=,tag:V+qTQUKDWDHt7MjEDMiq/w==,type:comment]
    #ENC[AES256_GCM,data:PGNyfiK5q41/o9djWtKggChDe4ju,iv:vXHb8YeGJci8PO4dkdmTKIP0nZ5LrC89K2D47yCy84w=,tag:EkpRItqsSBfFmJ8p7EsKnw==,type:comment]
    #ENC[AES256_GCM,data:l4wDbFXybP5LhLxTSUetZP8yInY0t852iA==,iv:fCvOZnM9QMpcCdhrHPPfj9mqFCSdLX4Xf3OldRyPYkc=,tag:Ud9lxyfodX/pFE/PgtSlcQ==,type:comment]
    #ENC[AES256_GCM,data:Hk1eIKleMKFqK0a9T2WpQIU9tC0m7u3hWAJSrQivvR+hwbG40MZjecFEmqV8KfHXHAFv,iv:UcW7F9ZNKFeFHHmrzoySIfA7TCNLevX5VVUisUzUlSI=,tag:D7S0TMt3FQwZoMNj0WCM/g==,type:comment]
    #ENC[AES256_GCM,data:z73ozb9bRtmmhptZNU/+HAhIPNh4,iv:xcjL8jkWu/xi2pPBWe1T+ckp10sTljKnT4dLYK5gAdA=,tag:6KMX1aacuy3aA0RFPTktgw==,type:comment]
    #ENC[AES256_GCM,data:Oj52Cf55kWcJfZZryAFKKyq8DppTK8CD,iv:Io6J6OAvAAUCr3h1jvBfuYynhKwLPuTV0ri2pz32evs=,tag:HX1EuF37gLsZjaD8m2o0RA==,type:comment]
    #ENC[AES256_GCM,data:XhQtJVPPgHKd6Wc6766xnHNUkeK3MW+Pq9xEa8eWw6K5QKeXKSUU8tzIbiremmS9ipM=,iv:olKXGmWkzM0H52EBwyf2p0HQtucvr29wjOroShDNc30=,tag:qpk3d4f3NGmB3QBmNlYpjA==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:KC5WaClSe46D+buevxb6msWSCsbs1HVw6ejHPGgFRlucMVu7IaptpMPcgUjBcp9nTCdUrN+X57MSjfW42Ve2jA==,iv:ch9hULQt/PsJ7oNc4W+HWIffJp7Rnu+OZNE2ObkGL+k=,tag:7XKctb6P11j0YZC0y2oebA==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:yEAJXOd8pekXEIjFwgP0gtCCDRDuySRwBbW0U9mKs9ZXwHH7PckcZHzw2m/+sPhzGS2Pg1F4pixgWVAjs6rfDfuRdg==,iv:bcQ3120zvS3zzH4JgRcEYSH/Rda/ki32hBfEY9UlGck=,tag:oadHq2HdufXYS0OAhHhEHQ==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:QLP3zme2rDCIeTVrp5ANROor+Y9aB978LOZQvHXhaSVdWDxdEuVaQvwHabq5TdbXyZDSPBeoILVfH75b8YOogIGQtJRQ6Q==,iv:jtv9PzLBpJ66gZOTWdhoCAGWaXpoa41OBHy6yzs6MpA=,tag:knDM7j5KQr0SQQp41MCmWQ==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:YlpPhd3qnvQsQBzFOALycg4Krg==,iv:85W4P2w6vnuBA2AjkVZDrof8OIotqccn81FK/ifD5zw=,tag:JnjE3PglJ2T1EUEg2wHMDg==,type:comment]
#ENC[AES256_GCM,data:u/5vDKtO1zsboRSA,iv:lz/cEuxBAeVDX34BGzSbu5sMIs9p8z8R5GzC1d+ZG/E=,tag:H4B4JZnIxabB8WruIAa5Eg==,type:comment]
#ENC[AES256_GCM,data:K8z3WVIhD4r3QtB2aL2eLNbA5Vclm5pXR1qX/vkC9qSRBY4AEtuUeONZvTwKfE4ADdPcDl6KXfdW2IJQZGstyQ==,iv:HLIZGPtfrhu/iQu5DoNPwtTwxBN2V5McTaMrzDiEwX0=,tag:cVh2FGJhb5ekTuvRfovMZg==,type:comment]
#ENC[AES256_GCM,data:JiS7iPGTckxW4yMky6YjteIL7GDTqPKkq8X/p+V7U/8juUBfav8ZK8xjX0A0kbxzGwFlaCtrHSBZ0ULOrH+r,iv:3aKV+ihuN+9EnvN9MorowbZv/JwTGAy5s+PcLq00qKA=,tag:e6lXCImawBUey1wEYHvabQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VHFiYTA5eUVsVUJTRzdr
            SHp5VlhQWHFWM1hWY0dkK1Q2dmRFOWQ4V25VCmlZTUhhZEVYeUxwaEdNYU0xTE9k
            aEVxT1RWZXJpSlJmdjlqTXlaMENYOGsKLS0tIG9mdzcvaGFyd05INXhhNS9uZm1U
            VXRMS3ltcWloR0RTdDhUdW9rNHI3RUUK79ODeHEBNINT31O1wBwRHLGSyl+/NhCq
            K/GF96quTfjVdCyJyXU7EjptSqKgEUuUxWDd+U+3ThJqp6WRkqF1Sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmpLZU5WdjBreStqb3Nh
            UkNxRm9tQWVsUjB0b2ZvY1dCUTlSZHJVcWpBCndzT25nUDByaTEvQ3NjWkRZZnNy
            SVVmN0VON052UHFRRll2cFpqZ2MxYkUKLS0tIDd2QWhZUUl0cVJFZUtFM1pHb2tN
            Mm5DaGV4NTRHNDl6N1BSclBDNnkvamsKva9uaf9KRVQ669pcckwSLVJCoxLaLzbY
            /3JOOTTYW+OLPG6JoPss5sGpjdG9F07cEXUGHGuocgO1dlkbvjIXkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T08:53:51Z"
    mac: ENC[AES256_GCM,data:njQlSVT9OegSdX8TXUpQqw4Wm4b7NPN8rh0CS7tHw8qsmKnKDD3wSeGlPLX4NvUHugWjteqM4E3gE/c/lJZ15HX4Vczli7b04dm2elEhJbdM56CFiYR5Kxkapljbt3yGu7cRM2jV+GDFN9A2SLzvWpt69U5I6pkYYDMlilN+UFc=,iv:gMxeGgj1eWbD+h6s0K5D4zFUZ8YG+6s6FYTQpymj6jY=,tag:8lSu4RsvOCAnMs58cWJzBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
