service:
    #ENC[AES256_GCM,data:afVKZt7L7/pLGbcnrrzceUTxauRp,iv:93lLpoOACTS+qoFHmvsdA3fsYhFbXtTeETURKLU/NVk=,tag:yw/nt5Mv5J3W6/NViu3f8w==,type:comment]
    #ENC[AES256_GCM,data:+8UeuLVmM7SbI39Y,iv:A6HAUnrDXRo+5szUSEhpnpSeCcQnc7K4nLrswiuU7Nw=,tag:g35vVL/SjD4iMt8LAxY31w==,type:comment]
    #ENC[AES256_GCM,data:J3tt7TYVGA2GuDZuYlQ8iXRI2S/i,iv:AGvJ4XhxkDN+9AFCeiFINZHyqUAtQNXtpcE5EkY6h84=,tag:hRPA2Zt4ITpPCXxgqHF8Sg==,type:comment]
    #ENC[AES256_GCM,data:6Q5NBP1czdwyHLcPSPcM65iY9cXKWqZ2Ug==,iv:Jus/gyHtzfbZ9SN1lHDpV09wvFPtp7j024CwsYEbDQ4=,tag:HeAOWdD9NXYuo2R1fD/PaA==,type:comment]
    #ENC[AES256_GCM,data:MB4lr+EkHW7euv+2GX98fiJ1exBKgMQTBFRPu94f+FIwsUEZqGYmwRXRRc0TK+Jn0uNi,iv:SUSIVtQNCdEUy6V6d5Q35n/7jF5WXZh+ocx33orylUE=,tag:ZiJpaUnlgXBHJKvMPQx7Ag==,type:comment]
    #ENC[AES256_GCM,data:BxEZXIY5L1Cxdc2HpKnwZTmO92Zk,iv:7oHtvZyetufRV56BU90trJV1Cb2d/4vgwQK2MTDAXsY=,tag:KzP+cW3ZxmYxKEeSxuj1Eg==,type:comment]
    #ENC[AES256_GCM,data:5w9iXQ8uNJ7tg4n1tGKv3LlXSl2KcK6F,iv:aZS+OS2XyjQpWty9HFVhorfwS1gAwS/4iJkyA82Rg1I=,tag:TC/eKudZLVvvfwzrYq9yaw==,type:comment]
    #ENC[AES256_GCM,data:+cSeUpsLC7RdhY44xNAJS/80hC6dqwdBobQjSunCulzMknOMl808MxZnJNlRxT4cgp0=,iv:YOmFo07w0qInDT3OONM2PEf5kWGfFlIYaAX/dSE3Sg4=,tag:XHpAowDQXGzIe5KMPNH3AQ==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:w9liLQA/CkRjCiWia4gFqYY/aEC4OMIogDE9UUdgfs18TdzVhrNlcq0cjK5uKs0fBwldLr25ngBWZb3/krwZnQ==,iv:Za/a/CQJPLCV/Vwhd4/ddKIfD+PHUVZzpM2JTkaZAhM=,tag:qiNdcy5qe11iuoas4Rq0Gg==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:dBspB9s1vBO0idimiz3OiuSVLs/pv7insUFOzK5Z+m7rd8dPutr1INZxZ8J5ALIbiZORuZOZd8wEfD3tjoqZJMffZQ==,iv:9oxACx7X/Lgs9iHRuNk0RR3mjsF2suiis40C2BByBTw=,tag:t3BKnGwDCcMvoNPRvFGJSQ==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:tpXGffJpcLWsfgjlaoFED3eamlTXnh5Dl52LBTfzcUfV8NIA37fxQBHVmDUQVWzOb3u5IzEn318j7Ex2SspRFDlWWIQd0Q==,iv:NquaX1hhxyq31CrWLB9ZxzKRqfnpyAQ1U669zSN4h6s=,tag:4+92aT0KMkLNQ5c5+h8WFA==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:u4sWBVxASUik8f0U+l67w0NYQg==,iv:Yh7eNzNg3t2fY+pWxWUVO3fmd13XBZ0ikGecqkziA5U=,tag:L9Bu5p9NygicoCcEJHJbrg==,type:comment]
#ENC[AES256_GCM,data:eBVt5uB/UNAlzmCf,iv:Pn0YwexASFLem9LsfMFsDKXYAHwuVyjamyiohPl9KJk=,tag:PPtIM2fru1pNgOXKB/dcAA==,type:comment]
#ENC[AES256_GCM,data:HZc53e6irD8EloIp97C2ybD9Vs4jNmDdX0k61lh4rh59CQRbic0uQqNNWqssPAWMTrGajh+76G47LcrtWPyKsQ==,iv:Oi8SMQMGHVZoze9fcRKRxFI8qBsheBF1OYYew5eRr28=,tag:ZoRX2fLvRw8+ndogK9jnYw==,type:comment]
#ENC[AES256_GCM,data:doA/MNpipnIEXlTZHzR+GI4N1BevZ3INOSK/+Lt2PeNs2l7nhthX5BTFW3X80nOe8iy9lYvq0ROB42R/l2of,iv:uKglRGJ/VwVN/knXQWmGf041V4bfWO1gacj8pPHDF50=,tag:MFcAipiDEwqv71/eWW66vw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYldyaHNCUXVaT1dNbU5P
            QUl5bEJEZ3hqU09lVGtVRTZRWVRCV3NHVHowCnpSZ2lxVnNidStNd3kvK2oreWhp
            Mmk1eUtWczVjSi83ZEZtcWNsTFpwR2MKLS0tIGpNUTdWWVIyWDg0OUM2RmF3L2or
            OU1ON09UN2NIUU1tTERKUTVmSHFvOVUKe2aD4DjUPFDW1loWQocx+TA9D7n/GRnU
            0XQC4TP8bRnmquh7vy7PODQo4n6WQrBzgpdL35OwRoxlqq4q47Gl7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK2U1ODVlQ2ZabmtZb0dC
            WmZxMEV3NDNSa0JCeUlaWXUwTTl6a0haVHhBCm1GVndmWWpCY3hMTTQwbm1OOEU1
            MFd1dGxTU2xaZlBSR3dQOHJwUll2ZU0KLS0tIDlPQVlVK1Z1b05wcEZncW9vMlBY
            elV1R2NTdUpKYlkxRG1uOHhBQ2hZdnMKzR+NgivuOHYREamkc+8GrUP3Z5TcCmz5
            SwYqulucb0yxXHBE2J36m80Y7P/uSGjQuxZ/VpxxIFpYqOMptYrtAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T12:10:31Z"
    mac: ENC[AES256_GCM,data:Dv99SKqgt/sOT05TOKAKMGWa9cMmpoo28euWvW5DR7nc43eIvWfTgqRgif61ujCF1MXyNth5fhMDGYAgcejDHRRzcargm6KGaxVc7VmfU5JgANNZ885rX+ZHTmi2V+tD6l3vKW2pa53rI2V+9JbGZeIjNk6StQ6ipQWONd78CkU=,iv:+GzUvxgQ9v6WVqTU8WuVLfB+M7YvL/TschKR0LJ0A+0=,tag:hlvMYa3mNguY9U1MQ0+WCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
