service:
    #ENC[AES256_GCM,data:O/n245qyoDBgvsc5SubFSbqUNij4,iv:M+4WqgNczYN7huSDXpOZMemm3q7Wi/1K1HMgcxKamE4=,tag:kbp9ioZUJVsamQ1n9wkzlQ==,type:comment]
    #ENC[AES256_GCM,data:33EvcQ3I7fCYr/Z9,iv:UIL2luI2WJyc+z4+e/r5D8a1RVei5QxJHPzBg//qEDY=,tag:Ni5RFHlhIp0bZZsDWXGokQ==,type:comment]
    #ENC[AES256_GCM,data:zcinjAxGFdHI5RwL1QXRtMT7r/PQ,iv:OkO+CrOZox9fiVgPwGnxt5zmGcvULCRhg8PkW0CzzKU=,tag:OtCxEnPxyyNk0VhT0+Q00A==,type:comment]
    #ENC[AES256_GCM,data:vUDEA3WMdBb0bmU8VqV5ggtbIZjvF746OA==,iv:oUAREfreCtUcZfjBMUBOa9aKeQUS1kMifV7v0FOqt6I=,tag:ABkqZZKD5FHcf6JB05+tCA==,type:comment]
    #ENC[AES256_GCM,data:02pebpTPaEsEoZpIm2TmCkM5ik2MHs4Rmyod5S16ou+1t7DCXOZV3W7GKRw03aVgMCgt,iv:Cgw2NSrfR2FwsdXnK/ek3RjvysyE3Vro5j1Ku2872KQ=,tag:ToCYkLfjUilFkWv/9/MTUw==,type:comment]
    #ENC[AES256_GCM,data:qnzhXr9KKKS5OTGeVfpnByvYws/6,iv:2CzppY9rUckd17+dRFeyIRzp4AHqfNlU6Z5lbWp/8Uk=,tag:CuDMaik44OFO4+8Yh4CaLw==,type:comment]
    #ENC[AES256_GCM,data:ciEtC7N5wYFZ783lxQTgbZGLWB4Vvrta,iv:3fI47coDF316LMEzAu4K50fD46mcT1dFQXSiukjXgXM=,tag:uNYOxoybW9uwhW6vjx67KA==,type:comment]
    #ENC[AES256_GCM,data:TGfOYHdVfBhNeS9zIyZG3o9s1GbgzNUv1974izxInwD/7MDJYXfa5j6ZvYuiN5BKA4o=,iv:OjKz9PxHB3oErEhSo7SiduGrDrekd7ikgDU0mAKlUHM=,tag:1Vzt9K8VMNTljZIZFTcf3g==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:UXYGt3QTZxYQmPTG0ckWLFH0Gle/h050xEomYEym3s1rPFSef3wzO1Yxqjr2G08niH8MihBUV7X8CFPhY+imWA==,iv:u/Y+4Si8w3YZPD8aH5krRldYD0ULKht9Hbo1dN3TsQU=,tag:2yONP75lmTm6zPRYUkwU0Q==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:L5dwnpRuf7/eDbgPh8OIT+OQ919+s+vwZeIWQYr5Y1nfGnC5RA537zPQUnMBIO7N8ZqKYDsFp88Wba2Azr6+XU2BmQ==,iv:GayhRSvoh0JBvPNzd5oDu1T/u/WM1cOaysZo7K0NCz4=,tag:OPHCgh5PQh4SaqWSBS/sGA==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:yyLFMAKmbgL5o+2Rys7UHbxWIP4ockf4HmatCUjAm5jibRx6pKFCbgExx5Rptp0bBXJD9i09uYrN+znK/yTQvMSbCOenvg==,iv:AeLrM6O1koMcPkIyfi6jcaaDCuxtUEBuPK1JLkky11o=,tag:lFjZQSz0VNFCN5SlTKHnQg==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:DUifV+Emzl4CkQvx+6+yMhIB/g==,iv:TT3plJhaw0PYnYGCFc11KnLOzu7RUAcbnMWsgpAhFjY=,tag:+Kfr0puBhPP9yKAixfKGGw==,type:comment]
#ENC[AES256_GCM,data:zdEpt+X7FGCxiQTp,iv:vs/kbnx1ZxB+Y9W2UWJ79nxJ+47+99PwjHHuPjhZjaE=,tag:94L9R9i8Wo3Mr2KwnL4bFQ==,type:comment]
#ENC[AES256_GCM,data:sCVG80WSJlY38A6tKmxyIz3DkyoLHRQ4GnuswsBLhXOtZrY7z6pqWxgZgivmtim/34iXLKmOK3vz68r195pr+g==,iv:ZZObDopDYpxmEPm2Un3IvP55Zx7zPaYO6FhyfcQugiA=,tag:4EP0di0EHRObXU66au2C+A==,type:comment]
#ENC[AES256_GCM,data:apHRWlJ74tJE3NumQYlKFlOJkFxIMe360vn5C4zCxaZg1DLTJERu/ezJYuIkAc+Ehzrql88+yD482MVgZ/7x,iv:B7GC3pIMMY5LNI7InWxzLO3oAgYXX1aWcCRj6mbTAN0=,tag:EhNkSZoIZWZ3Ym/lhzID4A==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFIzYmp0RytReEkrZHNC
            Y1FQL1V3M3YrTVpRWnIyTXBMMS9icTVIa0c0CjEwNDFpOFVCMjRTdW1uWm4vSUVj
            VlpsS3lqSWh2SkJwcnJPNzFaQ04wem8KLS0tIGYyd1BXRy9KWjU5amVsT1dHZjIv
            U2xTTmU1djI4Vkh5RlpTbi90ckYrODQKHKShxTKHiY+tIHIz8202bAJCxJp8tRc6
            XaLWoLCS7ouV268YUKkVX09f/6UZ7X2ca5CqAbAqVTpbBZM7CqplPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaU5ZYXMyV1pZeDdudnRt
            Vk1wVWJHaGtIbnJyNzhabEJ4bnRKNlVBdGlnCk5TZEVZWUQvN0F0SDd0MS95aC9D
            d1BDenZ4d3NUTk1EZVpQZlNoZklzMFUKLS0tIE5JaUtSd3BkNDZjZURXU0JHbHVx
            K1llRW45bVkzaVkzQlMyOE5Ub21PdVEKqhdqsRyp3L1cvAOVIzbu9QABw+UcEDPV
            cTGIHIihRXchaA+ZFdkSh0yp5NlKJxksbF/opLX739SI5zJTR2PDqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T16:32:48Z"
    mac: ENC[AES256_GCM,data:EZCojkqrqwfC7932y962U7cYkJOM6isw6BDHvV3KfaAejRY8BXlmqGAB06qovSTVtuvCW94yWat1BrtNR5gw353PVlh8EchtRsQQDHw7RYz38dIbT0dPLXLr9g5u+6SuEFihCrZXFUNolfEfh3oqDc+VdJ3tch2zji+pyB30zN0=,iv:bXoQdOpqryaOTTzp7z8OV8myKqBXL04nDmKlTCN7pro=,tag:lch/kpEYP7YuYd6OTWOH+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
