service:
    backend.$color.yaml:
        matrix:
            - variables:
                color: ENC[AES256_GCM,data:xogeIQI=,iv:hrIrzwWSh05b25JyAGNDs9ZebooiwpLI9iORV0BfYLs=,tag:zdpYq000sTr44+uE5BEkbA==,type:str]
                port: ENC[AES256_GCM,data:ITf9CQ6XRY966F2rCKge0GLh00oxKx3qSYCvPyF3,iv:+4Lw9CNs9i25stb9weB7gw3/2RWlgJ1iLqmCxBku39c=,tag:EG7Tv3CbGpkFzC+MitYYxw==,type:str]
            - variables:
                color: ENC[AES256_GCM,data:QPxUuw==,iv:qfRw8Ex4B5En/bB7fGgYUJO3Toy4K3gwgjhULM/AqEk=,tag:Rpp4XAzQ/hdYo8F5F7OLQg==,type:str]
                port: ENC[AES256_GCM,data:N1kVXcA8geTldYEF9CiMFzaC+8BpIwDo8ZITTmE=,iv:2gXytukOaf2v/ZRD8x7J+PrLYyyXMn3tykU8ywm+KZY=,tag:5HCRBJ7qhg5Bj2jfhwBWzg==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:eBzs6fpVJV2P7QQ3O+/t9GEaKvIMHIDrA7AjIUCIVSEngnB80U+Y3VXJLLthy3qiKornpCk=,iv:lGPo3KGFKETPn/b0FQhyof9VGrIMrUFnEzwRf24TLG4=,tag:nQvRiXdgaDG9gEHJ0QlJqA==,type:str]
            - ENC[AES256_GCM,data:QgdqeDVLDM02m9Y1FF6iohLUyjHbDHtZ2V6+X/fTX7CXIeXw8V83qVbJXFDTFGy4m6l+7A==,iv:+Egq7ycSvkptHAMloScrs+qwl7EJQARGSkkBey0EW1M=,tag:c59pgQeOtrAmJRGN2zlSNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb0ZUdkYyb0hscWdNbTNm
            c3ROMFdMKzRHZFk4a2ZsWHd3SEdRTDdTTW1FCkxiUForRFdqS1JwRGtJMWdGandB
            bDZVK3FTa2R2M3M3Vk9DMXhDVk83TTAKLS0tIGcxUG9sRENlU1Q3TUVvSEo0d3FE
            Rll3Ym45MzNWU2lEaG5lYU5qbHMxdk0K3khcI9+bKIucbI8S4h9nukiiS9EkwktZ
            Pr2l+U3jtEYIOj+LjJFexT3J3H/rANX4VuIf6UyBkZsbtWIrCo2QFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUktvUUtZV0ZEMzhlRGRx
            MWJBbENEZHd3WThjNW1zN2VzbGk3b3QwUXpvCjk1V2kxcEVydm5yYTRWNmpnMkht
            SGZzRVZFZjhiQzk1ZHhzUjRSbWQ1K2cKLS0tIDBhdXhmRUFDcGFXMTdqNlFPdzhZ
            T3lKdkNyR1lJbG5MRG04TnpRb1hnSzgKXIx0pSiaF41pfIQH0waBJIC1pY0MRjYG
            ov+03YjmWTx9IX2EbpbFimo6alZDc/KYFJwe11mJKireY/SPK20AiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T10:22:52Z"
    mac: ENC[AES256_GCM,data:nFGtGwb/S9em86vW1PJmEYEa3FJkt56avTFJdqvOke/eiiYFxbwh9rx+tlSUEoJsH38g8gNyJEiEFm++mXchsp4wn5ySsPBdjLc5wX+4N/LZzzfFppk5SKPYXn7GqgMduRP+aBe4cDAf0+itA/L9ziIcfOBtElI9EXX4Sm2DJOc=,iv:h9bnjpbHFhyRLHFMulPkCV4PgbqLahfH82IyECqANzQ=,tag:NtAXRsGvdOWPVTDODvOp6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
