service:
    #ENC[AES256_GCM,data:7fPqq0Q5EBwftkkkir6LOvPb+WrD,iv:2EkojaB+JX8PHf1Rt9rlBt3uhCXLj/+RcR1jOcTXPfg=,tag:z5IZbWEMuZG0LyxxYPH/dA==,type:comment]
    #ENC[AES256_GCM,data:e/wuExf+IyCoOwfe,iv:aR5+l1Q9jjDW3/KCuL2JgbyX59Ge0tbaBzFLmWejnRA=,tag:h54KcsRF2qHoHsuRxzGv7Q==,type:comment]
    #ENC[AES256_GCM,data:468iV66Y2cahiJ8QaxW1h2XiIzQr,iv:5T53IpE+5GWVknPv1kXP/2UcXiOnXJBffAduuLB/UCc=,tag:CMzSI5UOElnWu/6BlAmEfA==,type:comment]
    #ENC[AES256_GCM,data:MGvtXvKsggM9E0/EwrtiF0/ltKUjydx28A==,iv:aqK6nVNOX5Pu4KMCc6JuNafNB2pTfU/0O8MonAcoTN8=,tag:6DG2cBAKW0GlJINKHaVRww==,type:comment]
    #ENC[AES256_GCM,data:ZoexVwacWklr7GcwduAbFipWwAJ/ZTdVNN2bLq3VOk2BZwOTm9EmTIWcqPGS+Ge0oKMl,iv:x9UwNYTjxCRaVIvHuAIC+OgRSQE6CD5xdqFk6KTNzuI=,tag:bME0ipttb7jQUxupJ47PDQ==,type:comment]
    #ENC[AES256_GCM,data:jugxqnOc6K2W4yjqhsJXgsShgKxh,iv:TW7OmUZ5iBHyVEAN0oZ/CBA7Y2nByfrlPufuPtXsIvI=,tag:wcmreFUy+iGqIBfIidMTdQ==,type:comment]
    #ENC[AES256_GCM,data:C7Oy/Hw0sPvz24/TA8QVh8uHZhXKefgP,iv:CdTi4IbxmVUelQA1TOsD7xAcItu2y9lFRrVUdO2CqH4=,tag:X4Gh46aJdDqAsX4htzE9KQ==,type:comment]
    #ENC[AES256_GCM,data:bt1CPwmM5bGF5JrdhKoLW+7Rk6avMOaKmXTGsWw9DuSei5aKbAriZaqwslkZvOumNJ4=,iv:uidDZrgA/MsGzng7hSuPfxShMa/Gi9r3ey/dGeV73fY=,tag:ZMRLRlMcxnaCrRnJCg+Zzg==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:N0FVVVW7dd/6QgKf7L0613I6cK+rIueEprTeMYrCzNuhoquQ082QAFJn9DN3OD/IyDwl2uajMuqNDUILL/0n4g==,iv:gcm4BHnMo0cDdbfuh3C3kT73/D4nqrXcnNWyRcvjcpw=,tag:jG+1IIBItvQ7ORvD4Q199A==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:D/7K1fXIl/FnX5BiHxVHCSFTUZsddpjxqoly8e1c0cfRneSzgTskrEI3gm0h6fzBYerwP0D82ORNqAv24HV8ygcnBA==,iv:7ZKxKwb/onTWjdf3zGSwv7eCdbCZoGc7t1OCsQTZXc8=,tag:exFlcfLGUrmQGr/taniuWg==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:+BVVjOl4rXVpNSMmV3ie4cU1X2Tpw/Dh0xq1jbXSQUXgqHqzW9Xocwt4jS2FHSWiybH1M7zVBi1DlahUqkeqGCUZxWqdpw==,iv:Mg8hOmze7dWsafEywa30owyeUD7L1tHEfSSBS7NT5JE=,tag:RQ3Q9kj96QucYudJc9PHvQ==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:Om0fsNs4Fqvt3f2Tnjy3WGmPMg==,iv:w8Xiju0m9S9tqXruUObdOaeAz8UjMgfPFEpnJ8xw8XE=,tag:2SQ9m4tdoLJbqynVoHvytQ==,type:comment]
#ENC[AES256_GCM,data:Pjql4djv7oDjbgH2,iv:g3E0vtuSom3YhTWK5JgHg2HtaQCkddmiUzCdaK2A0TY=,tag:GmM+YqG9zk2Fv1T6JqniRw==,type:comment]
#ENC[AES256_GCM,data:o/WMJalQ47g+djUOav14uwLau2g3y7lcH/renJe5zkcNzzQPDpRqwCBf7Xl8lrAym0hdm/xNGR9LugmiSqFZSw==,iv:YSUx+y74yd+n5OGzpoWY57xd+eG+yRAchgUtzcfolHc=,tag:QeJhTwIZtai8xK5/E467tA==,type:comment]
#ENC[AES256_GCM,data:I241jBvmoQ5GKi7m8Ead5dqvl4LtEtesv2iV9qaGMpeT6ghrU6nmeIF/VO48jzbfiO5VXkTQ1uNdyUqzLcfJ,iv:sct+GbpkM3KKIziBaMjZaWEbCwoTnAXtg/Q2eNUbj+w=,tag:Z2mY8nCEoY3X+UA1WdM8Bg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjVDM1JsemZPRDU3OGdx
            NElCekRlbWxYWnZ6aDR0eHZ1WGNWYXBjbEdjCjZYK1owMHRERlhnS2lYTFFIVnBq
            SHJoRHpBUkczMjd3dGFwRElDalN3OXMKLS0tIE1OWHNBQ0xBUEpac3V2Rk5scUZh
            RVU5N1haK1VtMEtOSTFmZUoybzIrV2MK8S4hwP2eJqGVZ8eFpbzOi3+sNZuHy9qW
            VeKGQoMTcPlAPHW9RFj8PjuIe099I241qsphb+4rqhWrXKNBsMRflw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NHdoclBBT0xOYldPL09q
            QVVqRUl2alJEZzJkdUc1bDJQQ0ZKOUhibXljCi9FdVF5QVpXYzNwYW12M0hTTlI3
            RTJ2TkJodU9jaTJPcXh2Vi94bjdLN00KLS0tIHBPZEJhVFpXQ2Q1aklOUCtoUkVH
            NG1ESER6RVhBZ3FSVktBbkpTTE5OSjgKxLNkQyVFW+kNEtSsu8bh0AcsGtacy7l3
            f6YSq8EwXBHQ2cy5tfxU51XclpGgnsm5hDsPkwm8psIlzO/hBdIt1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T12:44:59Z"
    mac: ENC[AES256_GCM,data:FPmHM+8vZYTbeNZuwAzcxKGLosw2K5QOceImQmWpd5e/xlZZ8nAS0aWQNQlkrSWng4WALr/SOZG8pMcvGCcC/j4lAJLScCXVxUzal7QQLCJU/8tInOYEuWyeiUSGQaUhTjvxYMhD+hnD7cWbsyLeYm46md4aMKu3BDHOwWxSbnk=,iv:8R+lJ9Pw8il7xtP+wANK2UthlLnDF7SBW1gLniT1/A0=,tag:FiwPBmhyivForw56g1nHGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
