service:
    #ENC[AES256_GCM,data:3GEWGON3tb9ZIai2QzZQaPqOakKn,iv:SBAC72sQoTyYFl/H6mEIOvkM0iAU0fVUMmnUzouu7Pg=,tag:agZYEVYtrSScGCbfZj+DMQ==,type:comment]
    #ENC[AES256_GCM,data:6hlVhZIW30awEN5S,iv:+Nos8Hps2HAvqZIcL05TMxw4IU2+a7UtqZRkLPSXsFE=,tag:J2W6R/WkW7lamFX8dj28Jg==,type:comment]
    #ENC[AES256_GCM,data:oXGhxXvbQjO3pDRRkBlBpp1Q7ylT,iv:H0f+km1QWQczE2wR9HeXfKKYYVXRV8+vPeadMgJwY5E=,tag:JspStwuyZXsqsY76/EFbLQ==,type:comment]
    #ENC[AES256_GCM,data:FBjIVOEWSoPSuB1taRyD+xHT/YLlkKExOg==,iv:5R4z57y6MI+dF0bEcrbvMSZBwg6CVz7/QZMKFC04TCM=,tag:VyQKSRUrCokq1LavyB8fFQ==,type:comment]
    #ENC[AES256_GCM,data:KtO/ZQwpLMP5NFwxUrcgOaRSQiCP6MnOZYA8sJp9Uy9gv/zsMV3DWg3oAuPvMwiF9Ugl,iv:dmFfOuZCzbVrepw2Z7Sfb+YZIF05joA230CKwxYhoG4=,tag:aNQgYkheTC5BTZCil4hLzg==,type:comment]
    #ENC[AES256_GCM,data:anwpCDQ2e7N79rdwsU+o1jFDwCjA,iv:20pkCBnPVVkX9B1CwaVtYs/GpInquNKKXdvYhmTzz1k=,tag:nx43jS7zuMlBRJHOkoddbQ==,type:comment]
    #ENC[AES256_GCM,data:Tw1VBqVaHGxDBoDagJ7Jd/WMcLQnUAHP,iv:PAPCkm5WKHACd9AS4TJYH5O+vZdD6nu3Z9+1eCQCP5A=,tag:qFY5246xbJZf90YmcpBeXg==,type:comment]
    #ENC[AES256_GCM,data:Sd/6BHs22oX4488l5Q1/9MIRztTGNgte7wy37Vv+Z3twvFzc7ho4RLhr6mj37BgK17Q=,iv:FZzGt3rDs1VXH5zjy3KvTT7eAGZ1auDdOzV2uOe3VgM=,tag:NDLA6OuVST4NA8Ctl2FwyA==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:kOiDk5gELl0ueD3RijW9FgDrKLgWB9pAV+CIKXnTW+Y2iSfw7Nu2vqwd8UQhRrXzUnUc4j4YNRglO8ODQxusww==,iv:BMg27KZdXzfDQM4TWsjybQOLEHQ27YRCfXiPJxU2SJU=,tag:OZTU83vKkHPDRM7oQPBK4g==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:wisgEBO35k31FO5jFRiul9iDFQN/DzwJ7g1r+PtxPC5UcXxSSmVGJ/HrHxHVIPkpLe2I1cMLo8kup3lLwhzPcl4IiQ==,iv:QcS1GcPIDZaZAJ7EZmnrst+t7pDSEDnrXHG2PyzQRxs=,tag:uqvMdF5TmcEPblMcW1fL2A==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:Gc3U+2cwAsrKbCCnzLAsBsD4hRRrelOsQ9FsUilGACOkufDgxNq2GrcVbLglP8aJFRGiAXJ9jLVlwIa3fOJi237fk7A4nQ==,iv:OEuVi6DKnCLL0erw/slZfpTwE9O8lTmoqSBgyiZPzoU=,tag:PPAOxeWKzGSCXBETv7O96Q==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:RLK94Mse4UlekG8domfmzYQd20F0ILRgJWcU4riMr0Wxyg0O2jrZLDfaWtHznQ0DQjv9iAY=,iv:DEj+eeiRhtjtxDPP7hG6oi6fyIFyOtPOBhrgAgiJChc=,tag:UtEZTRJaxkmOvcSrgTh8SA==,type:str]
            - ENC[AES256_GCM,data:cmKBSvg6FjZZY9i1kk2xPzODUOTi9mBO8uBJKmG/aSXDKxIogn5fkcx/LJJDoLTkJ2p5zA==,iv:TSK2jWZ179DZOYIysYC0qguZUBoUEPjRXZOn30ElzJk=,tag:aa4kwkq+Ta7H4pvnwdH2QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQUhHd3RRRHhIRWhzeHgv
            SnRkK3pqek5iMkRCdDl1OTZPTlA0bjFxL0VNCjFXb1JTNWdiZ1RlZ1BPbVM1dk9J
            K09HU0xVdTVOZE1iMGxqekhObEE2WjAKLS0tIFUwSmt0VFE3YVVtbXgrckhhbnpH
            TkRYOFpaMHNGQUM3dDNRd294MUFrdGMK4gBBtdhRWd7AlPhs8kPuIwksrk7cy+C9
            1TWkBMZkSEgpqfy85VpzPG04NVGMGlVE2ULbWl7yrqY9ECEp8bDgbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanFiVTB3bFNOdC9LdUhT
            VFhOcjFBUmthTW5RSGc3TVFTY0trY1M1eWhnCjZoMitJZENJWE9vTXRJS0w0RjJC
            dE5mMzMvckFia3pEOGM2MDE0QjJUK3MKLS0tIHR4cFhFaHlqNFRlVThOcWNWYUdw
            b3I2TDAyeklQeDJMbGlnVStOREtyekkKpMQgPVg+Aavy3lxKHXKTfUeIaT/QtRvd
            3jVAyp+zs4zIkby0s8Z0X+NV7DyohKDgkg1hVpldNkTkSJtJ8/Ec4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T16:35:48Z"
    mac: ENC[AES256_GCM,data:EpQ6FtkM+225okxRY7od9EWV3rcEO2HR8LZ4KBj5K+lniNjvBZ4Ugncc6qqAZq0MPUV149zRkrD6RS7PAxaB+VwiYU+GwQkTovKcSfD2MxVPia8xz5FyFE17A1IFd9eTUWAh/Rq9nxmUpfg4JtWB645LIT0lfQ1fB0H+UXr+p4Q=,iv:nyDaoP9MVTTZ/k1Wlwcnnjm8XGfXzAjRcSxavFk9YXk=,tag:JEJrdhRVun3TSYBiVGrqcw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
