service:
    #ENC[AES256_GCM,data:B5IX/wNs5SzqHps9nPdqcEYAUYD+,iv:6yvbipzMxozu4QNHoojRwklswgoTx/usQi9XG5kP7zU=,tag:TD62L5+RJDiOueWNqmKVoQ==,type:comment]
    #ENC[AES256_GCM,data:6IlwcwK07a1oxccK,iv:NBXLrrq/0hNK21eHT/fJ1uaA8q6o9BxFeKsqqn2X410=,tag:aExKCy4jztZS5cnmu/cgMA==,type:comment]
    #ENC[AES256_GCM,data:9Z7cENQoJVnSJgqxql/7kRdT9dH+,iv:id5ODeNX3knoZS5QM6HHPs5L7nCVtZTvyYcJmLI2K8w=,tag:IAHl1c3cTB9rJMQw91SL5w==,type:comment]
    #ENC[AES256_GCM,data:741MBIPbdLIsNw5sn/QJwk244CCSCeOHkQ==,iv:NtdDLdvd4Iex2hgwgrYCQLoqVJdJfDDi9LppOP4LnGw=,tag:cBSHE09cSSbkEwOl9dhBlg==,type:comment]
    #ENC[AES256_GCM,data:5YwcT6rsqQOC/5n42O00pXw73/INIPX88QAdDbOPfeTJi+JPOXwXi4FLJ44JF5Yahctu,iv:lzEX/aVIOrmlYs9hMPEFM/ZA69N4Ljp6mAaEJQ1ADFo=,tag:I3r6uTJG6WxJPX98lalJLA==,type:comment]
    #ENC[AES256_GCM,data:t6UnPs6GCATB4zWaKXX5vqiJCynz,iv:bPEewzfpjsIfMjdLQD+JmIi7wfOOPzk1nn4i1weZ+C4=,tag:hvuknAKu++7DzGeYft18SQ==,type:comment]
    #ENC[AES256_GCM,data:qdomy5UR2hIiXDazMb+RXjmMJaTMZjen,iv:LZ75qUxFPt1/zkOvaD5RP0YKn3VRj4zmqNbh0TKS0Yo=,tag:QX8gXal3yiZVjS/x8nxxjw==,type:comment]
    #ENC[AES256_GCM,data:p8ifM979i9NV6IuWqiuDC6WBrCW8YanSV1v8bj8oY+GbwRTKq1UEXflrATYtBC3cAOE=,iv:nW1kKKN1Qq+zD+qH3mxfl0n6maADJCR4QVGCe44AFNU=,tag:9lbi+WgCq8ddD14DQRIWiA==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:j7vbXAXQRqaqr1wDBYKN6sLvt5Ommc2+TN+b0dWzT2ovFc7Ob1Co9T6MPnjk4drXo3wrBsehfD+lKBf4OCtFBg==,iv:9S1mxX6E3ThUoxIr9686bGA5HWCUrq4f/SLf1wh0MNc=,tag:fCXfSxDT+5Q/THH+fkSmGQ==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:KD6Ycy99AwHiURdaDynB708KyLsoWQpg9gx2UZGxXEi5EYBw0yo3JqxFooboy/qcqY8eqrb/bJ/vTPZPDd61eopvsQ==,iv:r2jhoOMWpb5cc/7emmJ0K5ilnnT2eYdltf+ggKzbji8=,tag:YDk702Xvrt6/MjAlOUUDTw==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:q9itmAjIvQA15XM7A8hGvrxBHUliP4HjF7KWGJwBDmq0tOCgPw4KFa29JlwZLhTKuqzjub5G0TXxw86RHN7AAlr0U0iU8A==,iv:Q0J9SRkA0K/rDaXIlMJxNDeBuGNK7e3eO9DthA3xDBU=,tag:/dWpe+/NmsoZPXUKbd8R6w==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:JlfoHl0B36iMwPJAyGZtE9lJ3w==,iv:1tGZ6iroMTkdt/2xG4ZZSxzOiGxOoj5a9QaDetOzKjg=,tag:nfhIGOS91t7KK15j6q1qug==,type:comment]
#ENC[AES256_GCM,data:vvdJ7Afnu3d8x0kn,iv:zAkxRZ00G8VQkUPROE9PnDQ/OM6yW2CpEhpXVKmDqFM=,tag:GG5ONeIRLei0sBRgS26tpg==,type:comment]
#ENC[AES256_GCM,data:FZdxE5ylcdZDxXdCjpVNutldnjN6pQ8/V9XDLArdHwVtkBd1udIeLENO8kJt64+G0nARz3IjOR/xIwJRz4TCjg==,iv://55unm+i51wRzoheURcLXtqKSUUXXwf2jVP21HZnc8=,tag:dERtLpyiuoOd1m1lNxOPuA==,type:comment]
#ENC[AES256_GCM,data:PE2jQFpySi5uLyHtbGsnkDfjLhkbFGv1HrIqToOmzXcSRA4TfSYlccYl7wxQqmYYCbVodZWbs8MXi+rHzwfU,iv:/O89JMoEh9hD0XtBY3m5eU180cOTELIWJGFX2kr1TSM=,tag:yrP2yW1jUE6XkQSpIfzwxQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NnZuSERhamtnMVlnOU1Z
            VEtiY2J4UklrM1Blc1FyRnZiVVRhWktyOVM4CmZUNnIwUGhFbXZYZnZEVVNIam1J
            YUtoVDh2MHF5UGlpcWVHNHc2VGZ0M2sKLS0tIDltU0xUWDVVaUhqclpDUHloVzA4
            TlBCWnA5Z256Q3Z0c3JyTWE2V0VkTm8KTNXBnclDHCC6HZp5gIGoowSZUhqPXnhH
            qu6Zz9SPU2OypBS5W+vfCEcRLo2XUsceiP6zcaYuIg+Zz0qMHktn6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3REs3SDJOMjRnbmx5eXVD
            VE1yQzl3bG5FeHQ0a0hOMTM5c0YyNUsrU1NFCjVJWVVVRVR6VHJZTWFvdHdoanBL
            eWhXd2Nsb0pjdHYxY3ZiUjFlQUxmaFkKLS0tIHRra0JsVnA5SnJwZEovUHl1V0cr
            OWxPUC9hNlRsQ1BnT3JSbjlBVW5YU2sKgNynD7LGSxnqICEspipRc8WHXlWbNBmf
            POLLwOTWCr5LUTlc8fMwD72+IO023IcXA5ddnRSPWq24myP3HoMPTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T11:56:18Z"
    mac: ENC[AES256_GCM,data:IyMBXmIxtQHxAkgOFFmUfUGe/tFXGtORKK5sbkXQpaN8iVydvxP2p6qwZIE6nM9+geMhEguRJrQEPKFnUuTyLYsydyvKBThylp1xsyuzeKwEXn0Ao3aOaCsSPX6PaJZbMGBSfDvcRgIXnxNOSPYPxOWgXtNh76o0Em8E+iz3dEU=,iv:yAtAXjfWHHU9l0rAmZNsgb7lU7Ylx+uNh0AFU5oeAgI=,tag:4jC6fz6RKBcIFrTC2BKZZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
