service:
    #ENC[AES256_GCM,data:qLJ5Eqszz+j1osAmiWlaq3/6sv4L,iv:yppDDZlFALA68IETVPoN2108yhswZPGY5DhvtrT+A6s=,tag:YwhbvwrmwYC4tqQ0Yy0nnw==,type:comment]
    #ENC[AES256_GCM,data:fG0DB8DWm774JuY1,iv:VgWGsiOmqHOuXZFpiqQpyChqqwD0LdsXQlwiNMrPdb8=,tag:ltZJFmTZ3Lr2exFH9Oyl7A==,type:comment]
    #ENC[AES256_GCM,data:D2HTVHhI5ie5bfWwYG2XEjaQHPKw,iv:w2//+kkCehjpG2HzTB9xvWvU8kpbqO6YU8Etx2WY4ec=,tag:LBosebJiqfb9Z6D+eSTv5w==,type:comment]
    #ENC[AES256_GCM,data:kGReTQSLCmMMA1aWcpKwPMdxc37sMxMt3w==,iv:X1QCVXuZvD2WHsOUbP7rzSGljtMWQQN1HZQIVYYs0M8=,tag:yh3qf+Yqhbl294ntpDumcQ==,type:comment]
    #ENC[AES256_GCM,data:yEMAIZ09h0OybkPz4T0+OuzxaWo/L1wFEdRZ6CcpKeLv6LhXUto+gGCWUPPxvQsKviwi,iv:9+1htFAmGO4CnQYHDXaKpscQHhNDQuqCENxTAd2gonI=,tag:ioih0GwOopozr2/USVz3yg==,type:comment]
    #ENC[AES256_GCM,data:q4Bi08VHwk2t8WK+k6y/hlUM+7Be,iv:VIxapeffsHY/EcDrp0Kr0VJFfVTSnVB128SchIbE9Kk=,tag:bVsPZxr9uK/Cm3fKwVyU2g==,type:comment]
    #ENC[AES256_GCM,data:50Ot7VhSRSio2tLxKwo604+nFw8lYa7Z,iv:RhrPjoXwXCp/I0sd2Z5Q49fXT+nobivYIrNV86E4SMs=,tag:saW1OvFvv8BfOvvea1o1eQ==,type:comment]
    #ENC[AES256_GCM,data:sx9XLxZsQSY+XEmQD6XMoJpZnV9aaWA7Epj9NMNRFWxuCB/Ce759T4pzCTBg0U3540s=,iv:60Xi+I/cX7DCam/KEfa3rM60FGzasidmA2Q5XIsfxRk=,tag:TuRSJDOA5QuriV17eCpqGg==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:qpUOGYVTWjSw3GswEMlsojsQhUwQ17M7AQVBO/fvGBpvnKulUs8Gw6LaRfptqr0AUdqi6iyefiZSqLMAzQArYw==,iv:uAt6LPFeiJy7CdCKGTvNFnIndfMVL4u+so6FiDIoe+o=,tag:/Wjqk8L4F7QTNcLjssUZ6g==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:cD4OSNqkGxRN7K3AWh9Gx2JCdqxqNx2+wtkMfrQvlOalvhnadcIQ8cxSF20DZZA4U60GG+ngQ+PpF+lgE5ZwgHwTlg==,iv:hqpmddot1YALetM8+PTVl0RO/d6m00v6iAlZ+5dFWHc=,tag:ktwe7dCdXB+La54cWpEpBg==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:OIkXaZTqLYvmVpkGkZg5Ds87KJyKFkhbL8n65Us2jrvQ3ycb4F/aLeiR7wdzvVvZZPXRHcrvWhG7rkOdgkUs8C7hNEbZ/A==,iv:Zwtu099f+GT3Q2GnXqAVUuYQOMCo1dmRWoktVQbr7WU=,tag:/cAPY06DR8sZ1R6YNPjAtw==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:9T0VjsTmvGg64zTlTWMh7S6kVQ==,iv:LpC7vT9mJCp86DDIgA5qCgJhS5XelA5AcXLGLhZERDI=,tag:5Ed6xDpfH5NY1VQwbLaLvg==,type:comment]
#ENC[AES256_GCM,data:vI+GvBAR9rWpTYci,iv:EN7CQDAWBRe4/DXjblobN4mz6vJRYdO5vuYUeIdhN0s=,tag:EBMG7g+ww1WcXpuy+mFUXg==,type:comment]
#ENC[AES256_GCM,data:K5j8k4dH69l5+msrN9lXlDcdVpouWO4kdFHBmmmwdHapFdVmGbGUOh9gW4ACJdDifY+rrHsUb9rhwvgXCdsSJQ==,iv:JOxKvRIUH4JvHBQnNMzaFCwna9RhepBPBjFBtHfy4Ck=,tag:MixryRsoxnhbzs39vkWCHw==,type:comment]
#ENC[AES256_GCM,data:NgrhyOvaumhXpQilhsqpOC6TeS09DJu5EPMFn2GJM37sDMrx6IRpEAMVThLP9t7A4JaToYOCcA+ZMbzzHbQP,iv:PMp4PKz9ZOALRH2RCLxHdxnHLgHoVHQnqw1E3uykOUA=,tag:lSMQIxd20Z9bmk+DTmjBQQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUXhLUWNyT0YyVEs1Smxy
            NEFobGlpNVNiSlA2TVNUYlBhUnZNamxJYmswCnFIcit3YWJudlhvaGp3K1RuVEc1
            MWVsMHFzL0hxU1VEYUdFSkptWDhnNFUKLS0tIDBMbU0rb1M2d0VaV0piemMxdHlr
            WDIyWGF2VURYdXBubnVHZU91RmE1QWMKkkn5iHxBgh2Yb6wHr42NXlrzPgjZOLc2
            kCs1euGRxEC9QwVtA3AIbfcS5B71fsztChW8UgGy8fPf7A/6pug1fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbXV0ZFk2bXEyK2xVZHJp
            RmY3eVpOUE5vR0E5VGNBZm5zUmdhTFpCNWpvCjR6elQwVjdMNXFEN1JiM2hnRi9q
            bUp3OXAvZitDK29LTjZzdFA1MEFKMU0KLS0tIDhkMlZpaUxXZDF1Yk83c1RDZnk1
            TTJGTkk4WjFVaExiVllyWXRlQjhBNGsK98HBFY4JWvDRFeODeJHQq1Ai5pSkfPmD
            tmhfHkhDuWhTOWxIScioBAWzK3IZNG1YRvf4L8+Ivzhphc43TMxC2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T17:36:02Z"
    mac: ENC[AES256_GCM,data:0ibablztExZPeOa2Zta5uRfvmInuRbdxGypTaVjgFmFOGKd/kYzxXRM1qtYlhb5vGbhpQi1krOpnytaQhMwTIOrEDX1ctXc5vzYCjHm589mkSNc849fl6F7I9c/QcSKjob2gtya2cztMg+SUA28uJwreE55N7aOjLB76gclQSgA=,iv:2gOYdG5TxhRGQvTE9GcSH0mHeqOlxSda4fWjCNpVf0A=,tag:z/eFJxqqdOiM4IBQRn2qdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
