service:
    #ENC[AES256_GCM,data:VMF0ZfOx7STDLXb3OX8wou7xao5N,iv:rHMbIkhkBC4oWIEl7EryyS2uawjwleMEfWE5sJpDp8Y=,tag:nXsW1qrzJh7VNh0DGNGD+Q==,type:comment]
    #ENC[AES256_GCM,data:y3yaev+ZcVwy153d,iv:yylfCOPMGlC6FWb80mYf1N+5TGWHH1Zg8uVt8vofexw=,tag:2NvZ3yd1Z5vvBzDGj0czQA==,type:comment]
    #ENC[AES256_GCM,data:mZ3uKCHO7TQNwevlhmhJ7RG40MMc,iv:PKSnVaRS2rPIaibA+/gACmVN3oynwJ54+vcV/d7QhwY=,tag:LXwS1MgR8RGHqpml/AEKBQ==,type:comment]
    #ENC[AES256_GCM,data:t8PWOwuyWBjECRb1OKVkmo/jR06w0lPIGw==,iv:eqQW81BCFevGsh7t5/MjiMr/jL4RxnrktiGhWYNOjYk=,tag:TbcOioqgY7gjKlxQuynlEw==,type:comment]
    #ENC[AES256_GCM,data:t/bDCYfNTnoAD6Ggw1rkFnzTHvH81rkn0RaVV26TkzzVQdLorZXMFd56dXLlh2VWoyge,iv:eIgIvfyIFNjSET/dLzE1+2w38J0IYxJWITRrU/xCBKw=,tag:P5IaAPs2BWNVyu5pBqbH7A==,type:comment]
    #ENC[AES256_GCM,data:1eNfzlQtv2rx2i2FQX4jaesbQ/vy,iv:x5iQpvWVXZCRJIGyFpBmsIcqC8jcMeA4pCFIeS1f280=,tag:uzJTs3Qf+WrpH+dfLW/l9g==,type:comment]
    #ENC[AES256_GCM,data:Ff1Qyv7qgz9hkfEbZNQ7OhGy/5rAoznA,iv:1j98opMqchp3/T3nrFYLa9p6iC3nGpqp23u2EhMYmOQ=,tag:pHQw5SOt1kbYDKHntgwhAg==,type:comment]
    #ENC[AES256_GCM,data:XWGATtW/o/D3hrYnLRAmoAB6/G4nkWpmpFWPSYOwrth3Z0hke85KMcFGqhhXtSAByKM=,iv:aNu9QFs2CgHWkxn2VDl7owZz5xj8phlTR9agvY3A7fk=,tag:1on3ZAKpdNTIJJAzt1El8A==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:9GTjOL2+omEYrQDcYAzcRkia+47irraSrj6RtbbbN3IGP/QEqsT2EcZUQvVD2e5tbpAzAkB2LzX3UtBQ32tzPQ==,iv:p2wCFJ7Lr5yyZBP+cC/Q/tX5WRfsakESRMpBi00P6qI=,tag:EwBOiMFstrYkhAkfpyXVmw==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:4kIN7mbRJe9sFLH9jg69n/ljAS8ZCYwGfVXiOgFZtBmAVnCiT/P91wPWI9CI24pAc5gqVTQFG+TgVd021MoLDTxz/A==,iv:eANcHv1mNf6PmzIE64zOeQJ/CWCGxlNrE92x444/gw4=,tag:vvIyoNr3U0qf4N5Ba7nphA==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:jLZpw9AZQhLa51hy3FmDy98JsIIPbNWBNhhKetkh9A28AnMcTklr91MFtssNuFtVc50x14y59WMBT+m37XE60eUjSJ+5Ug==,iv:NBSV5F6/FNZIbOi/Fuh3OKAvujBTqo1Jh8oXCc2mSuo=,tag:qGKqLrSEUaD2gp14rj/iNg==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:IT6LmwES1K8S7ChNm3TOolp/1tTP2XHdZ+Iw6TUir6O6vl8Uf/yJ6mOgzXkFnBlavEF4l9U=,iv:90LzNIERIXxqSu1puZIUZVokXkI3s/aZ2A+2fJUreLA=,tag:4l2on2es3bPrXngLzy7iEA==,type:str]
            - ENC[AES256_GCM,data:veptQqDxUsrB99pAfxS2AYA3A1TM/KA5a5yqePMSvnhlLPzAxd9EXX+frzsN6Am8TKWZBA==,iv:9SNwlnpAKP+/3IHvTH3VaG3GJTiJ6D7YFz9ur6Cnf+M=,tag:qDhGjvsF5sSKs0a6H3DAgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OHN3dS9vbjkvMTBselZ1
            TnNCUGlZeCtoM29FTUxVd2FuV3ZnTmhPeldzCmFkaUhaak56VURlZ0ZWYmc2MVBh
            N3FYV2JwVDdiYldjTmtpbnBraUdYdTQKLS0tIGhibU5JdC8rMjk4NGV0WUJiSUk5
            K2cycE9TZ1NZYnhUakVjbkZoc1ladEEK0xEJoMPo2G4221AygIcbyJxdJDq8Bk6o
            0qYdEnSo3jzC7ejwdXOumLqO8a1rgnQrw4oabK83rzt+ZvXNUvOOfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc2RERHBTT3N0UDA2M1lG
            YjVBR2NxZUxzenBrUjhYNnhYdkIxcWRFVEU0CjVWRzRBcFUwYit6NWZZdnZtVWdy
            c3l5SkgzWDhPKzVsdkxwZzRpNDI3NEEKLS0tIFE5ekR0a2lkc21GOG5zYlNrTVZ5
            eWM3azRQOTQ1ZkZpdFk0bzZsNVk2OUEKVB7dQP8N9+A7efWiWmA+53sCyC6Rwr/S
            BZC51fkhwr1r7XaH5i+TAoXwJ10/H9/zSi6Ljon7qHQdoOuv8e/vOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T17:52:27Z"
    mac: ENC[AES256_GCM,data:4B/qPTCoYyW+UZVROMD50b97JD+5BF9ghUo55fXNxcyfw2sCc5W0gYnrwChQtCwcqjD5Rm0CuQNBFe3broccQppl8jF5sQ2xx7raHUjQt3vH8VEErt0eleJJ0bo6UdNP6cZo9pAWCGxhtQ2MBlCwkcH/SDfwIB62gvcdtmc4j0U=,iv:CVNJSrUW5eYQPvAHvemDOdRFcTdWgzCvoutZQyikc4g=,tag:C3/vtNPRW1vgElTlo736Xg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
