service:
    backend.$color.yaml:
        matrix:
            - variables:
                color: ENC[AES256_GCM,data:F6TlyzI=,iv:tG+RI50sgwOg0Pr8d1H55TwktuD4Kn6rJGIMSh/w0DQ=,tag:3pb1JBdsCo/ZmZHgBguRtg==,type:str]
                port: ENC[AES256_GCM,data:LiMYz0ObpkfT92pM9teous8Fgu8FZrkMtGg6morI,iv:WZ1ClVuSb9AP6/I5MXmwh1qoVCoUJnNpo5Gms6SSY+A=,tag:LD1mMZMEtzVXx6YAJfBQsQ==,type:str]
            - variables:
                color: ENC[AES256_GCM,data:+zFozg==,iv:6CHFoKddBkt4ACq9LRI6Rwor1cN051pMTVJzvgQb22s=,tag:JMrun2DUa9hchxuKg15U2Q==,type:str]
                port: ENC[AES256_GCM,data:tuQ4itRLa4rkem1rzJ398IZ+HrLH+mL0Ag7iNrQ=,iv:VAiSnAPUnU9vyfLEEvHleRC6HFr6LH3KeLecabKjnoI=,tag:KVGpQFtZe5IB1g7wqH7KTQ==,type:str]
dotenv:
    mudev_backend.env:
        linkTo:
            - ENC[AES256_GCM,data:dRWYNDctK+FuQO7alySHkY4K4eumiaSOCfk9ghkT1R3DyaRQP1lz/EkiIJsWYWHZBA/lzvU=,iv:5MfOVGKWZX9ijyuS+DpGadjzDzyzZH8rA55+uhw2AmI=,tag:ORQutCAPR60toVxEKkAc7A==,type:str]
            - ENC[AES256_GCM,data:sqW7yQRAsmYQL3CoQxj47KbFOG2KnaZF7ZnCs+/emDbZVQ7SeikqdfSXN7sNQ4NME7zmmQ==,iv:zgXF0l+edB2r6B310orOWdEf8wyv6MmWH+C1Kfgc/lQ=,tag:9gEY/9rmLtPr+qQymNBSGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycEhoYTQ4ZFFZUTk2T3BD
            NlN2OWNENWszS0RCMjBpTWVhV3RNNWdXUm1NCjFRWE5ubGQ5S2FZN1ZIdmZqQ25G
            aThseWkrRGEwUmlZdlZBK2haOGxjTVEKLS0tIGc2czRDZXV5ZWxuMVVVWTE2ckJT
            ME1EQ3FPbjE1cVJTeXNkcVRpdnd2S2cK+9rnzV0X0xRL5zI+1v1KfPcdZS0sog/1
            jaqc/VOfYK//N1985A0pHiZOQ88TP7I+6qg9pKLDmjeoMsqkBuPvIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUnN1WlErMFlTc04rSFZ1
            bFJieHdDUEIxR0QyMnpwczdrYVY5ZDJzQ0cwClZuUzc4RFBlazhvM0V0c3pJK0d2
            U01Ba3kwbnZ2bGh1aXJxVXUvRkdGa2MKLS0tIDVDQS9wTTR3K2c3VFgrUytVMkFz
            dGpYeVl1ejZ3emczWWE3bVV2a3pGRHcKLt/8MLZY97/t1lZCV7VIbKQgM+aTODWl
            1fj2ojQlWAWsrawRhUCvzdeaJnMMmG1voJxDv5w7cAmKmWFx0iWutw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T13:04:50Z"
    mac: ENC[AES256_GCM,data:dqkVY4zXILVFu/s6bFHM44l7vfIn5t0hiqrY1OwaFFBk5ZP7luUhB/CYvu8zR2F795ZzKJvUGZAbbWg9cFwYvdZ9yV0TWDiQVM/PeGSedPlA5g7iBu6X8AoekQ47iweQ56Tjk+yR7zV0IopicugN73KI00PabSHDZo3jNsapXnI=,iv:d7/GmShlc7znjgG7DY9CEZuHpjTlkhxFqO3JBdugcjo=,tag:2cCkkuyaxVjhdkaNf4M0Vg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
