service:
    #ENC[AES256_GCM,data:x5h4QNECS+xuKDZbi67itCbp8Y0r,iv:0orSt15vMjII+G1vlF9dBqYr4BTL2UYZSZ7N/6mp79Y=,tag:MRzbsAnFKFOvvb9MHuBCwQ==,type:comment]
    #ENC[AES256_GCM,data:xRg63tWNVhgO0T7m,iv:6jG9BvAZ2o6K1r2/QpOIxpAi7oFo9ZRfK3qW8OQp1oM=,tag:xk5nkR/2Uq+2AdqnLhhIow==,type:comment]
    #ENC[AES256_GCM,data:xr5J97+reb+WVhzGRrrFgNUKeT//,iv:2rE+FuWtSvY68/RpPUOjZYxqbuDRD3f/5RgVJomiIkk=,tag:4PN0WltDgzWrNlJ6rw5uZw==,type:comment]
    #ENC[AES256_GCM,data:+SMsYDO2eIOQkJBmdt3WYRPHtOAbk3d7pw==,iv:gm8m4dwToYIFPFeMnebDS0OEkm4tzPFtsPtqEkcdSWg=,tag:cfeL7M+riK0y/REWfHaTEg==,type:comment]
    #ENC[AES256_GCM,data:47T+SjPh6ss9Rm7eY2LNBY+Q8uZSh+WqXw87JnZq0cHpDRFhaZouSv5qV6UFqgTiby+W,iv:25KL7zlczZ9TtABDIgvK3oZKIdi1G2aOvI4r6JrUc4g=,tag:ieSDXwj+REHMnA5FQ37Smg==,type:comment]
    #ENC[AES256_GCM,data:32j7AmJLdR5IMAzuFJOc+rWp+spG,iv:P7RI85aqkGhVNqkSXULYCVMZSZSYOeGEpjAwt/HiPQs=,tag:rVNg5vP6ojlQMPEjRHh0Qg==,type:comment]
    #ENC[AES256_GCM,data:TyF9pNi3QwS6EWqtjGlD5daMc8OBQ9vY,iv:YL+XEMFkivTcz9OJUMaUz+y7tvxhhZiTFscTMN8wufQ=,tag:7UEllD044tqisOs0D5Hi3Q==,type:comment]
    #ENC[AES256_GCM,data:ueroYoRzcXEgMv5At1Psbol2apqdLyfBY5NRUZ8O5ME2anWXauRzVL6lv0hBMEhQkFg=,iv:RQmfg80Mr1IXVuquPtpH3TrK3zJ6JREjkZetSKmZq1Q=,tag:N5Xwkot1dBQUjZ4hSW8gmA==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:KwA7lYC/oAn3hpFh604XSGhJ4q1ybn2d7SC7b0CfkGU3+Hegl9/eMjs1mVvwbgzaPc+XjacBAjvO8ihY/fCH1Q==,iv:3B7bgJN5z22x8T9Iwpayv06QelMgRYVVsDQMiae8FeI=,tag:QSCuvAEOeyCoSXQM81WPAw==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:NfW6GCwiMaF1rgIYHr+4KuSBF1ok6FGIhdcwelVTRwhEr0uNk9b4ZKPuf3mN2wKGjUe8TyqMFgJ7v8mF8nlT9TS6UA==,iv:4gHxSqL4SAnVCYOVcWTZAhbKfXiiATZcFZPNiIld8vM=,tag:tchcKoX9+CXsR7imuVQWgw==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:wX5jtCcCrG9C5ESesp7JIzf6mubOk2Yqm5tf34nwPLkSQ+zkw9z0btomA+W8pkgH+eG0gjwYNe03KPjjspxehCPlH5aiAA==,iv:LFUbNEiQLYZRNXUHT8gDFlzotvDcMzgg22oBh3GEEJQ=,tag:3lAEm6SnabKKFfdOqsN7MA==,type:str]
dotenv: null
#ENC[AES256_GCM,data:PXcpCUjAB/ZiI9YipItq8vMLWw==,iv:bubPD3UhMFOPqVkMJPtQHcOe9J0oC24gjGXW7YMK2EQ=,tag:Sco0VifXnFB90ftKwEX9/Q==,type:comment]
#ENC[AES256_GCM,data:N1Og07iTkLLwziI/,iv:M8ujVCrI0EdInxWjWJBAkb4XnHw6eG14dF9nPBEk93Q=,tag:mngWZe9B4BtPp8pU8WDc5w==,type:comment]
#ENC[AES256_GCM,data:bUlgVPxum6SvpY0xtdkWv9vvdUK7t+r2XKRwVcBRfqMvPyOYuGJ9j0FEyBXE2QRUANYMHbW/+ZjwwNCDNe/Z1g==,iv:qznLiC6hoB2OwKi3eIJVfZ3IBvwWYKO1No+rPRdmePs=,tag:AYzUc7dKmYG+N2L5SJMrcQ==,type:comment]
#ENC[AES256_GCM,data:BEYnYtLvtoycxH6/6aB9QReUniFqW9FpeMQ+al9yb8oFCF3/fRQgwcBKsLBOh4xhvWuijeyuCPHxvtZ4/oZn,iv:xzvfzhrJRPGSgJleyVvo3TA6OD89Qp1RPOCJ6SuM4EY=,tag:Q0d1ZmQo3yRZ/9dDXkSpQQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZTRrK2JEMkttWHZUY3Jy
            WjF3ZXl3ZDNHOXdqaW9sLzk4VVowa2kzZEU4Ci8rZ3h2bGt4NVNVM1ZXOHJROUZ3
            VWEwUGtsNHpyL0lsb1RjU2swbjJnaHMKLS0tIGJvQnFHSjBVOExrNXprQno5cnVO
            U3BzYXM4RG1kdnRUUnkyWkxwK2RraXMKszyU+15fYyAQIK2TAEvhxQD46fY5wTvR
            srjhKSnwMQARdHZHL6O9f7mUxIYfK9TjQ0Z2dxYrua/YJYyx+BO1og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOVZ6UnNHR3I5bWRTWmZT
            bnltUC9mbnhva2VXeWlLRlVpQUVYbGF2cG5zClpxQ05SQXQ4MjRpRFJVSklyWUFP
            Ny9GWTBDWTlhT2NBSDNrZmp3S3JFYW8KLS0tIC8zWHN1aTJoQ1J0Y25MQXJHOTUz
            T2lYOWtrcWUxYjNaYWJZRmF5Tkg0QWcKGgyLQ9aAAFnv6oISdGAwu0l67vT+4XL9
            X+PCWJ2czO4mK31QrI72prCewmI2sp4SGUKWg4JEpEI9/PpUkzwRlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T14:54:55Z"
    mac: ENC[AES256_GCM,data:Ag9fvw99Y2MheEKYAphOeJ6Wq/18INapyDDVShaVoB/L/mAD7bZV/V1NvWLZweeK2yG/WxhQKduF3FObFwL11Mvj4sU61btcK9Z0MZWglzaVsY9VrzQ5QqLt+TLk+yIMDX/oq7Yj5zTL/VEuAwXRsG0oIzQfIDyf7esesUew24I=,iv:ATCw5R9VbE20MsfYrBwhZiLHASjZQ3Dhb2ewrvw7ce0=,tag:HT1oVOLKw3j3otScN2YGRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
