service:
    #ENC[AES256_GCM,data:ZBDxXpRStXfRQk9d1NcvQnOQwicS,iv:WBd0Zw7bGjgDEtbuSJ30SD/Aqm7BWsnNZ4BDHg9ChGc=,tag:7PjHnDM4fbkrnOnl5vrXpQ==,type:comment]
    #ENC[AES256_GCM,data:tBVDj6Ik1TkV8/k+,iv:2W2gkvRjvX/Dw9Z436Odg4ZKe4WdogLdaLaQIh7ZgLY=,tag:hki9G6mxjbDWSHLHyakHAA==,type:comment]
    #ENC[AES256_GCM,data:9g53FWIvObNDM1REjutE+7zEotmE,iv:dpW5N79NcpL1+zI1Fg0Ftn1ERI5E9i962fePPSa6gW0=,tag:iJnpjDH9mzrjR0F+I8HvqQ==,type:comment]
    #ENC[AES256_GCM,data:waJW/EDsz0koohwyiKUpukJt8S7KmBwsUQ==,iv:GP8T1Y2IZp8qVRrF2VntXGjnt1a5x8dTE5+G5gnjiXo=,tag:cuSLVMWxmLYml9+4kfXzBA==,type:comment]
    #ENC[AES256_GCM,data:jYuliTBlO/B5QrXE1aLjTS/UNf3PAtT+3h/kFJhjEoME3TVddoSbsjCGVL44IBCpvfgw,iv:jQcL/a3eNFZv076TXb0VAF/4yNtmnyVS5JPvfPrUts4=,tag:dd27R/vKCyMz8JclAO1NwQ==,type:comment]
    #ENC[AES256_GCM,data:02aISTr//yUeNPiAj1f0yAWzJ+vp,iv:d0RseArbvSmM4SA8Y+dg2LFk/httiPFiqgIh4X2MJo8=,tag:KdTA7O+c1yaubPWzSWj+JQ==,type:comment]
    #ENC[AES256_GCM,data:eocl6qNlSSByTS6zN9hU/lJTX0KISc/0,iv:hIPay1G4CJ2N8IIoc8CASpZijBHcYnF32hHme6gp2eE=,tag:QwqGQjR5TbhoP5iodhdCLw==,type:comment]
    #ENC[AES256_GCM,data:JpRR5LXOpALG0janAqhTHPN/NhTJFhAqD9SXpnTUBsbCXucyTWrk6D2eKwvggLobvQE=,iv:DeTZ6402PZbBZTeHcpuLyi3jb1x/gXnUJc3Rix0geDM=,tag:x6OKAl6GWD+xGl6MCkE6vA==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:4BclRbE85fUoZ8eb81e4szpws0km28zoDwNDC4sq4rKVTTW2bwDjIGyDeAfCuBC/h+LkNedqFu1DeNMyyKuMiQ==,iv:cgGsk6E/JRkun/X1A7XgNS6ia3XmJoznFB/LzneOhJg=,tag:Vmpc0bdeG4z5eyfC1QQq0w==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:ajy3ZvkzjkxWj193MftAostfFvU6S64enTuuiFGpXmK/OKSZuyUApfpfl645+oZGU5SDADRZFzepBcgE7hg9bjtLSg==,iv:zAoaAHm4ugzJ1wdsHlgf6VwzzecQbKh94MhSIu8MhrY=,tag:CNPHMZNkS4b8kvFgx5jxVw==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:I6b0GLfFbtsk+g4fHmZV19DHE9SxpzXlYr/HeqOCk20IVr4qY+SOdL+/vBZQQnvERikMfTjlwMl4bGdwDpYZtR+rilgvhg==,iv:B/GpxoWPN75TJgk36jLK4UA+h20p21DydH2EvAKICCk=,tag:y/g9RTRAmCe358N0F47caQ==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:uOVrZte5aicPngkOMbU9rMUvDQ==,iv:fbvhkOTPOuDzvZB18aVTpKQIpjCy8n0rsL6TZUNONxo=,tag:q4HUivs36+uGqXEYEmj2aQ==,type:comment]
#ENC[AES256_GCM,data:B9jklLX3/bGhytTn,iv:7q3dt7TVZdCDPJhD786AFg0DjoBbzuWHiDzmtr1VIy4=,tag:xnDU5iOKiTWKlAlzoXup7w==,type:comment]
#ENC[AES256_GCM,data:mbv3i284f6TvnU8hkil9/6teupRLXTIEdJSDOP9Hsr5oAsuXd1y44CNujzpvhO1m2ktSZqM9fMGH93+bAigsSg==,iv:JYjoh7Dm6fVMeqthW4s3zfvpjetHEomq5C2beS/rBqo=,tag:ILdCrZ7m2bVqcvPw/EI+nA==,type:comment]
#ENC[AES256_GCM,data:UaCFkRY/7gmBtFE8q8rc2fmK3WvnyzFHQ5t58CO6dFkUF/95VbDSa9mKRhSdjjbcO/I+myaP8hHzLIYDmtA1,iv:bISfEUTXhKRdPrTd6uCM2Y4eqNO3ArR17ggL5cOf5W4=,tag:a/xrq3KIVBkakauaZFFCdQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia1VGRllVZ1Z2cVRRQk5i
            bGlZenIrQ1lGREJuZnZibUt4am5tTUg1V2xJCmwzSE92K21mRC9KdFFYM1EyVGtH
            cFZXdEpTZnB2cW1Yb2FYQ3QyU0UwUVkKLS0tIGo5VjBzSjhrRVVrUVZ1R3NrSmhZ
            dzVVYy9tb2VHKzdVTnplSUxOVk5PQnMKa6cWDIrZDVCN1TQGY9D9+8nZAjtv5HXj
            M0O74lfd9ZUXog/d85OMDnosRZUKuNpJ8MWhpSUumdhZH6fZvTr3+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd21HQTVZQm9rNjJhanJT
            SzBIaHJ3R2FTSWNHTDdEdHBXSmd5TkJSQUM0Cm8ya2tYVmtTK2hERmtlNXdjQ3dE
            K3htMms4UXY5UWw1dGVUdFZ6RkY2RGcKLS0tIDRyZStSUktvcFkvZk0vN2ZSL1dU
            SFVMcERSNzhHalNveGZ4b0l1NFdpU00KaPV9c5pqxUSp34thAdJ9/t3Fb4gpIkXU
            nVDK76bn5LdrH71XJc9HICbffmSA23Pw3NIpi+rBTMeLRGg0pcrtTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T14:55:48Z"
    mac: ENC[AES256_GCM,data:gN070KHwnDQlYxq/fT5bRd3ZGrGN0RC3SZ+QTxESLLaCzXFIfbGVgCuY1FZ2uT+nzxFAupibgRkSfK8giHVMvhV8CLxkBgaf7YqG1l1L4PfFPAUXlOrWx6jwZ7/SWCtwEgYo6MH0Ut9xZZ+hXKcnQzSOXmGWKzd1kR/ngNhcM8g=,iv:lyLmXlrwTCpSRQjqM90RT+b1F99KTC8NwphkBxJQjpk=,tag:NpF9o5LQ6BLGJqSLTvX4EA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
