service:
    #ENC[AES256_GCM,data:Gcgfs5rPvSBfqhxRLqYXcMXyi/kO,iv:hW0vuGYV3h/m0WlioslZ3a2zknxu02jGDeHCVjg/NX4=,tag:IcF9JamwGDQoRB2JD25c0g==,type:comment]
    #ENC[AES256_GCM,data:22rFIuCTubZBANDx,iv:0WDreojfaht8bySzF60qeov4m6lV6g1dYzACxN2MEK0=,tag:tVBD0wFIY2ToXvoALDE5Dw==,type:comment]
    #ENC[AES256_GCM,data:34w8BtJ+4c7czIy49N52gsIpESAk,iv:fvoHaHD1PBITntfVuyIG1P1VCT325V2FQPtmcsrny2s=,tag:zgGDXBj7BjOMKEBC+ZRaHA==,type:comment]
    #ENC[AES256_GCM,data:Kq93oXzmjAom18MBJzGzXsBz3kusqCz2Zg==,iv:CxOzgV7IPSJylwHiFPI9yQCBIbKysvw7UTXZMmU9/LA=,tag:BqcR/et7V98xfsdcxEiC1Q==,type:comment]
    #ENC[AES256_GCM,data:hWSkIf8UUVfAq36pKaTvU/fH/ClRfoRwlA4oPiv81vYFhNXEYeHc2//+keQuuVvfByW/,iv:1WMsOID8imm6y/ns2gwyFTcR0UaeY5kOmK1LEcq9jiI=,tag:oxxMDllSy8EfikRyMbiG7w==,type:comment]
    #ENC[AES256_GCM,data:OE18U3KElcQiSILJUMKMj46Rz7yA,iv:o0bVqwdlIkjak0or/A9NgCXa3GYQ5bZ83OaXQZst9W8=,tag:DkfxpLasV7OHlbjx9m5TrQ==,type:comment]
    #ENC[AES256_GCM,data:3k+tT45uCNOxejo1eV9LQx9My9V6S7Lo,iv:c27hsVN0/l23FQrZEVXp2IoKkn887ueWG/LQrCYlsAc=,tag:ey2ylRl+3r5cZHnbmHAQ+Q==,type:comment]
    #ENC[AES256_GCM,data:WvP6JPIYIKRNh9mdl+VOVXbNn6w+TqkyMxnhEXm/nRcZSlhHcPwzCIGCbOd0ybUIP/k=,iv:QTahlnde7zh2vgTozAPZshIH9ynR4f6WR0CtFfAnyQU=,tag:MzteBqG0uU49hjHv/mfOpg==,type:comment]
    jupyterlab.yaml:
        linkTo:
            - ENC[AES256_GCM,data:Tt/GWol3RsxYTTRpStd9hcc3wC2jxBi9+hT1m70kG4q2hRHV4I9CcXU6Zp5cd1itBwppWIYY3hEvUIh8NyhqXA==,iv:Krow9Bi0o6sMy/n945dsKUH+nhW9hcnYAWkNITPzp/M=,tag:s/+v86MasmhCbx4k4Km/nA==,type:str]
    node_exporter.yaml:
        linkTo:
            - ENC[AES256_GCM,data:yDP1JvZWgNoUJu/50RjhuHL/Im3Ay4D96/GixX9S2Oh4vD0ktvfyIeRKLSLpP5iLxVQMwU/ggFHcR0BGghTp9Hca1g==,iv:WX7ga754t8epTpqCQE9DF68JLw7Ln4tNCeiOwUZTadE=,tag:ioKftFJNTFOGS+ELDQ2Uqg==,type:str]
    ssh_vultr_tunnel.yaml:
        linkTo:
            - ENC[AES256_GCM,data:nI6petlTRHPOkSFZErP9/1Y+ytpSG2NavlG4j/KpsTpgWzUP+H8hVmMSilZtR9WRQHJr2u9mQv1b8KF69QYVmkwh9iVZCw==,iv:PuSX+WnskLZT9eVjGiKdzSHD5jMaQr+IhOJWpuU4oIc=,tag:2SaK7hcNaB+9Ve4oVLYgnA==,type:str]
dotenv: {}
#ENC[AES256_GCM,data:0M9kg45bu+2W1e7o3ko2P6SU5w==,iv:aC3D4t/rp4bFEo7VsGmkam8whHm4KnrRleqLs7Q2t0c=,tag:qnIFqJ2PKsutzcGw9HvsDg==,type:comment]
#ENC[AES256_GCM,data:ZORwQXWGRaV+FLhW,iv:qvsHVNJleiLGgkBxDuzCy+HqL7x3Lct18TqF/5dg7sg=,tag:gOzeOIfnLDRF3K7KVNqWFg==,type:comment]
#ENC[AES256_GCM,data:Gm8oldBOnDGXUbe7fq7Nrm2L0WfErbIzzTJtw7xq/yUp75RSArtyhA5F3go8xynfB6U4Q81Gnr0r0kgUXwnn2w==,iv:rkmWiJ1lQAneh/FZQVnYJdeUk/4QgldvLq9c/DQECKs=,tag:azHiW9s5cvPmQrbMlZlALQ==,type:comment]
#ENC[AES256_GCM,data:WWVTqzYNaDE1VM/gzEy81kXqL44XXcRqiPdDW8M/T/eNcpZa9pRJNIEnOkC2mQfF2eTtWhdm7/6hwEdeKxrs,iv:slHcjYHR88+wkBaTT9+ZSu/aEB5TI+enIdNSHrJ0k9c=,tag:PGILocgTij+x+0lP9ehZWQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nyf66nrycpqa0fv4q5p0r78jzh4gdxnkp58vl9rc442lutec64gsg3ahd5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeHJpbURDbFR6NXVpeUR6
            QnNZdC9GekhuUC94S0p3MlptZXN3WjFRSG5JClAwVGRCUDBiY1JzSmFyWjArNkRD
            RXo3ZFRKV2k4dEZaNDRhL1Rtd1BndU0KLS0tIHI4cW9NeDA5Kzc2anNLbVF0d0Jv
            ZGJLSDF2TElXMGlaWCtOcHEzMGpqcTAKPkIqwXthCyLmvhUW90oX43hSlbp6UsSJ
            Hq2lHLFYPlmkI2y+xXA+OnFjikx23sDc8a+Zf9w4KxF65iG8n/GjpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q43cez33sf3s4e5fpq0hpj8k6ya9uveefumtq9gv4uxuw7hgt5uq9avfym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRXA3TjFxVm5XVDJReUVP
            a1kxSVRjQTNNL3VzQmY2WG4wc3Y3UXBSN0I4CmFVdVlER1RGYm1kb1RxK2NURzE3
            dzhjaWNLMWxhQ1NEa204REtpQlpzd3cKLS0tIE14RzdCYktmUFFRY0I3WXhORHpB
            a0dwTzBtUGtQeGNXZGxmc1Z1UExRWlkKsa/xjajbtND6yoSWBScb6Yv+WrblP6M+
            n9EG4Fu/LwuhBsCBKKfC2c+89QLNQdAgJ0rJ/WSZ8nU9o0H2NwsPAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T18:18:40Z"
    mac: ENC[AES256_GCM,data:c6br394DYsWj3s/Lzvrk6QPuJU+Xy3tOBRbcpyuosBV8MhBPBFKFyh1rmYdo7fcl6UYPiB6Lerm63fwxQGmoZYQMxvQpqNd0eX8Qp0NEsJ5O/+tmyEOEqhKsnTiUcgnSq4YqCJID3sAKDSSd0hFRUx1PpxxM+p5I74PXtQ+BjwU=,iv:K/nLkXo9uR+fS6H3KY8O8r2wCPM7mMxZWCOWV7XctDM=,tag:w11eBm0MCMShFZr/4Dy0gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
