version: '3.9'

services:
  mulab-nginx:
    extends:
      file: ../include/logger.yaml
      service: loki-log-driver

    container_name: mulab-nginx
    image: nginx:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 127.0.0.1:${NGINX_PORT:?Please create .env file on project root and set NGINX_PORT}:80
    volumes:
      - ../file/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../file/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - mulab-grafana:mulab-grafana
      - mulab-loki:mulab-loki
      - mulab-api:mulab-api
    networks:
      reverse-proxy:  # For accessing to reverse proxy targets
