version: '3.9'

services:
  mulab-postgres:
    extends:
      file: ../include/logger.yaml
      service: loki-log-driver

    container_name: mulab-postgres
    image: postgres:15.4
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 127.0.0.1:${POSTGRES_PORT:?Please create .env file on project root and set POSTGRES_PORT}:5432
    environment:
      TZ: Etc/UTC
      PGTZ: Etc/UTC
      POSTGRES_DB: ${POSTGRES_DATABASE:?Please create .env file on project root and set POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please create .env file on project root and set POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USERNAME:-postgres}
    volumes:
    - postgres-data:/var/lib/postgresql/data
